### ISSUE TITLE
Deprecated: github.com/Azure/go-autorest/autorest/adal

### ISSUE THREAD

**Issue by ricardoleal** [grafana/alloy#1205]
### What's wrong?

During our security scans we have found that [go-autorest/autorest/adal](github.com/Azure/go-autorest/autorest/adal) is marked as deprecated since March 31, 2023.

There is any ongoing process to update the [Azure SDK libraries](https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/) ?

Thanks in advance! 

Ricardo Leal

### Steps to reproduce

Use alloy arm64

### Configuration

```text
$ /etc/alloy/alloy-linux-arm64 --version
alloy, version v1.1.0 (branch: HEAD, revision: cf46a1491)
  build user:       root@522901b7ef35
  build date:       2024-05-14T22:39:12Z
  go version:       go1.22.3
  platform:         linux/arm64
  tags:             netgo,builtinassets,promtail_journal_enabled
```

**Comment by jkroepke** [comment]
The mentioned dependency is a transitive one. I could not see that alloy directly needs adal, but a dependency of alloy requires adal.

As I know, [go-discover](https://github.com/hashicorp/go-discover) is one of them, guessing it may takes ages until the dependency is gone.

https://github.com/hashicorp/go-discover/blob/38e67cb5b4c0e71f481ecf8c76d6688653ee0b1c/provider/azure/azure_discover.go#L12-L13

**Comment by ricardoleal** [comment]
@jkroepke yes, I'm detecting it in other places, like k8s and other `go-lang` based tools.

Let's wait until it fade...

I guess we can close this issue.

Thanks.
