### ISSUE TITLE
Breaking changes to component.InstanceID

### ISSUE THREAD

**Issue by mwear** [grafana/alloy#1323]
There is an [in-progress PR](https://github.com/open-telemetry/opentelemetry-collector/pull/10495) to make `component.InstanceID` immutable in collector core. It is currently a struct with all fields exported. The fields will only be accessible by getter methods going forward. Here are the occurrences of `component.InstanceID` in this repo: https://github.com/search?q=repo%3Agrafana%2Falloy%20component.InstanceID&type=code

I believe the only thing that will have to change is:https://github.com/grafana/alloy/blob/287775c7545a648e054d4fcf15f2f2ad03b75aa7/internal/converter/internal/otelcolconvert/utils.go#L14-L16

The change that will need to be made is below:

```go
func StringifyInstanceID(id component.InstanceID) string {
	return fmt.Sprintf("%s/%s", StringifyKind(id.Kind()), id.ComponentID())
}
```

**Comment by wildum** [comment]
Thanks for the heads up, we will make the change when we update our dependency to a version of the collector that contains the change :)
