### ISSUE TITLE
Add labels map to SNMP Exporter

### ISSUE THREAD

**Issue by mattdurham** [grafana/alloy#1324]
### Request

Allow SNMP exporter to have a map of labels per target. Similar to the below in the labels field.

```
prometheus.exporter.snmp "example" {
    config_file = "snmp_modules.yml"

    target "network_switch_1" {
        address     = "192.168.1.2"
        module      = "if_mib"
        walk_params = "public"
        labels {
            "env" = "prod",
            "type" = "router,"
        }
    }
}
```

### Use case

Adding these labels are hard using relabel rules.

**Comment by bergerhag** [comment]
It would be neat if this would also pass on any custom labels defined, when using targets from a discovery.file, like the prometheus.exporter.blackbox does.
