### ISSUE TITLE
Alloy doesn't update all components when changing config in a imported directory.

### ISSUE THREAD

**Issue by ante012** [grafana/alloy#1348]
### What's wrong?

In the example changes to components/input_otlp.alloy are not picked up by Alloy. 

It happens because when the config is first applied `loader.loadNewGraph` reduces the graph and the input_otlp -> import.file edge is removed. When input_otlp.alloy is changed only nodes pointing to import.file get updated through `loader.EvaluateDependants`. Output_otlp still points to import.file in the graph so it gets evaluated but because its exports haven't changed the evaluation is not passed down to input_otlp.

### Steps to reproduce

Step 1: Start alloy with the following config files.
Step 2: Change something like the http port in `components/input_otlp.alloy` and check that the change is not applied.

`config.alloy`
```
import.file "comp" {
	filename = "components"
}

comp.input_otlp "input_otlp" {
	metrics_targets = [comp.output_otlp.output_otlp.metrics_receiver]
}

comp.output_otlp "output_otlp" { }
```
`components/input_otlp.alloy`
```
declare "input_otlp" {
	argument "metrics_targets" {
		optional = false
	}

	otelcol.receiver.otlp "input" {
		http {  }

		output {
			metrics = argument.metrics_targets.value
		}
	}
}
```
`components/output_otlp.alloy`
```
declare "output_otlp" {
	export "metrics_receiver" {
		value = otelcol.exporter.otlphttp.default.input
	}

	otelcol.exporter.otlphttp "default" {
		client {
			endpoint = "localhost:4317"
		}
	}
}
```

**Comment by ante012** [comment]
I'm also very interested in contributing a fix for this issue.

**Comment by wildum** [comment]
I confirm this is a real bug, thanks for reporting it and working on it! I'm assigning you to the ticket
