### ISSUE TITLE
Use cluster name in alloy metrics

### ISSUE THREAD

**Issue by petewall** [grafana/alloy#1364]
### Request

When `--cluster.name` is specified, use that in relevant metrics, like `alloy_config_hash`

### Use case

This will help differentiate between configs from the same alloy cluster or different alloy clusters.

**Comment by f9n** [comment]
For those who need it, you can add cluster label for all metrics as below until this development arrives. We deploy the Alloy to virtual machines. While deploying Alloy, we add the `CLUSTER_IDENTIFIER` environment variable to the service definition with [ansible role].(https://github.com/grafana/grafana-ansible-collection/blob/c0dd9d6fc192757a44d6c8082e474712bcf3acd7/roles/alloy/defaults/main.yml#L30). 

```
prometheus.exporter.self "default" {}

prometheus.scrape "selfmonitor" {
    targets = concat(
      prometheus.exporter.self.default.targets,
    )

    forward_to = [prometheus.relabel.selfmonitor.receiver]
}

prometheus.relabel "selfmonitor" {
    forward_to = ["..."]

    rule {
      action        = "replace"
      target_label  = "cluster"
      replacement   = env("CLUSTER_IDENTIFIER")
    }
}

```
