### ISSUE TITLE
[mixin] Cluster config drifting alert cannot differentiate between alloy instances in different alloy clusters

### ISSUE THREAD

**Issue by petewall** [grafana/alloy#1365]
### What's wrong?

If I've deployed multiple alloy instances in the same k8s cluster, in the same namespace, but for different purposes (e.g. one for scraping metrics and one for gathering pod logs), the "Cluster config drifting" alert will always fire because it cannot tell that these alloys are not meant to have the same config.

### Steps to reproduce

Deploy alloy twice in the same k8s cluster, in the same namespace with different configs.
or, use the [k8s-monitoring Helm chart](https://github.com/grafana/k8s-monitoring-helm).

**Comment by nervo** [comment]
Same here, with https://github.com/grafana/k8s-monitoring-helm :)

**Comment by gaantunes** [comment]
Fixed by https://github.com/grafana/alloy/pull/1679
