### ISSUE TITLE
Add alloy wrapper for groupbyattrs processor 

### ISSUE THREAD

**Issue by MargaretKrutikova** [grafana/alloy#1483]
### Request

`alloy` is missing a wrapper for [`groupbyattrsprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.105.0/processor/groupbyattrsprocessor) from [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib).

### Use case

We are using `alloy` to scrape metrics from `kube-state-metrics` and apply transformations to make it OTEL compatible. `kube-state-metrics` sets labels of the scraped pod which we then want to pipe through `alloy` processors to change the names e.g., however, from what we have noticed, if we are using the available processors like `otelcol.processor.transform` the attribute values get really screwed and it looks like a randomly selected value gets applied to the attribute value for the metrics of all the pods in the scraped set of metrics.

We suspect that the only way to achieve what we need is to use is [`groupbyattrsprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.105.0/processor/groupbyattrsprocessor) from `opentelemetry-collector-contrib`. What it be possible to add a wrapper for this processor in `alloy`?

**Comment by MargaretKrutikova** [comment]
Tracked in this PR #1300.

**Comment by wildum** [comment]
The PR has been merged, I'm closing the issue
