### ISSUE TITLE
Add a kube-state-metrics integration

### ISSUE THREAD

**Issue by ndrpnt** [grafana/alloy#149]
### Request

*Transferring https://github.com/grafana/alloy/issues/474 from the now-deprecated Agent repository.*

It would be nice to have kube-state-metrics integrated to Alloy.

> [kube-state-metrics (KSM)](https://github.com/kubernetes/kube-state-metrics) is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects.

### Use case

It is a de facto standard for monitoring Kubernetes and comes bundled with [kube-prometheus-stack](https://github.com/prometheus-operator/kube-prometheus) (and the its [helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)). Common (bundled in kube-prometheus-stack) dashboards depend on metrics exported by KSM to work.

**Comment by marctc** [comment]
The original issue is moved here: https://github.com/grafana/alloy/issues/474
