### ISSUE TITLE
Helm chart should restart the controller on configmap change

### ISSUE THREAD

**Issue by MrLuje** [grafana/alloy#1530]
### Request

With an existing/deployed Alloy instance, when updating the configmap the controller should restart on the next upgrade to take the modification into account.
This is usually done by adding an annotation to the controller pod :
```yaml
annotations:
  checksum/cm: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
```

### Use case

Right now, we have to manually restart the controller (deployment in our case) after updating the configmap

**Comment by jkroepke** [comment]
You can set `configReloader.enabled=true`, then alloy do a soft-reload without require a full restart.

**Comment by MrLuje** [comment]
> You can set `configReloader.enabled=true`, then alloy do a soft-reload without require a full restart.

Oh, perfect ! I missed it in the README
Sorry about that and thanks
