### ISSUE TITLE
Add support for sending data to Kafka

### ISSUE THREAD

**Issue by paulojmdias** [grafana/alloy#161]
### Request

For compliance and mostly as a gatekeeper to have a buffering to Loki, the logs should be written first to a message queue system like Kafka.

Having a feature that allows alloy to send the data to a Kafka cluster will provide the ability for the users to have a buffer if something happens on Loki side.the 

### Use case

Read logs from any Loki source, and send the data to a Kafka output instead of directly to Loki for buffering purposes.

**Comment by disfluxly** [comment]
If possible, I think it would be best for this to be the Otelcol Kafka Exporter.

**Comment by paulojmdias** [comment]
Duplicates #290
