### ISSUE TITLE
Add a new field to stdlib's constants map to expose the remotecfg ID

### ISSUE THREAD

**Issue by tpaschalis** [grafana/alloy#1633]
### Background

The remotecfg block contains an `id` that an Alloy instance can use to uniquely self-identify with. If not set, the remotecfg block reuses the `agentseed` package UUID that's stored in alloy_seed.json, in the Alloy storage path.

In cases where the ID is manually set to a certain value (eg. constants.hostname, the contents of a local file, or a hardcoded string), we'd be able to use the same expression to obtain the value for another part of the configuration (eg. an external_labels field, or a relabeling rule).

On the other hand, if the value is not set and defaults to that UUID, there's no straightforward way to do this. The only workaround would be to read the alloy_seed.json file (given we know its location beforehand), decode and get the value from it.

### Proposal

I propose adding a new field in the constants map as `constants.remotecfg_id` that would expose the ID used by the remotecfg service so it can be reused in different parts of the configuration.

Another way to achieve this would be the proposal in #1597 (which given the Private Preview status of the remotecfg block would give us more leeway into what it exports), but this is a more self-contained and bloodless change IMHO and I don't see any danger around stability.

What do y'all think?

**Comment by wildum** [comment]
If the ID is set manually, does that mean that the constants.remotecfg_id would need to be updated at runtime?

**Comment by mattdurham** [comment]
It looks like the Remote ID can change from external items so hesitant to put that into constants, the intent for constants so far is that they are unchanging. I think exports is really the path here and pro that aproach.

**Comment by wildum** [comment]
I agree, also an update to the stdlib does not trigger a re-evaluation of the nodes that depend on it.
