### ISSUE TITLE
Missing debug information on `prometheus.scrape`

### ISSUE THREAD

**Issue by braunsonm** [grafana/alloy#1647]
### What's wrong?

According to the documentation for Alloy 1.3, debug information on the scrape targets should be available on the component page in the UI. https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.scrape/#debug-information

Unfortunately I'm not seeing any debug information reported on scrape components.

### Steps to reproduce

```
prometheus.scrape "example" {
  targets = [{__address__ = "sample-endpoint.com"}]
  forward_to = [prometheus.remote_write.example.receiver]
}
```

View the component and notice the debug section says "No set attributes in this block".

### System information

Ubuntu 22.04

### Software version

1.3

**Comment by wildum** [comment]
The "No set attributes in this block" sentence is not great but there should still be some information under about the targets if there are any

**Comment by braunsonm** [comment]
You're right, not sure how I didn't see that previously.
