### ISSUE TITLE
After uninstall on Windows Alloy stays present in program list

### ISSUE THREAD

**Issue by ntimo** [grafana/alloy#165]
### What's wrong?

When uninstalling Alloy on Windows the "Alloy" Programm is not removed from the Programms list in the control panel.

### Steps to reproduce

1. Install alloy using the install on Windows
2. Uninstall Alloy using the control plane

### System information

Windows Server

### Software version

Grafana Alloy v1.0.0

**Comment by rfratto** [comment]
Actually, I think I see the issue. It looks like it's added to the 32-bit registry, but then on uninstall, is deleted from the 64-bit registry (where it doesn't exist). 

cc @mattdurham It looks like this was a change introduced in grafana/agent#6550, do you remember the context for why?
