### ISSUE TITLE
`install-linux.sh` fails on sha256sum check in non-English environments

### ISSUE THREAD

**Issue by yzqzss** [grafana/alloy#170]
### What's wrong?

The install-linux.sh <https://storage.googleapis.com/cloud-onboarding/alloy/scripts/install-linux.sh> script uses

```bash
echo -n "${checksums}" | sha256sum -c - 2>&1 | grep "OK" || fatal 'Failed sha256sum check'
```

to verify the downloaded package.

In non-English environments, `sha256sum` may output the localized string corresponding to "OK", causing installation failure.

Fix:

How about adding `LC_ALL=C` somewhere?

### Steps to reproduce

None

### System information

Debian12, amd64

### Configuration

```text
$LANG=zh_CN.UTF-8
```

**Comment by rfratto** [comment]
Thanks for reporting! I've forwarded this to the Grafana Cloud team and they've fixed the issue.
