### ISSUE TITLE
Update otel to lgtm task to use grafana cloud otlp endpoints

### ISSUE THREAD

**Issue by erikbaranowski** [grafana/alloy#175]
### Request

https://grafana.com/docs/alloy/latest/tasks/opentelemetry-to-lgtm-stack/

### Use case

When this guide was written Grafana Cloud did not have otlp endpoints for Loki and Mimir. Now that we have them we should use them!

**Comment by daenney** [comment]
It would be really lovely to get some documentation that details how to do this. For example, when I login to Grafana Cloud, the example configuration for Loki only includes a `loki.write` stanza for Grafana Cloud, not an OTel Loki Receiver + sending that through the Grafana Cloud OTLP exporter. Same for Prometheus.

My tracing pipeline is OTel receiver > memory limiter -> batch -> OTLP exporter, and then Loki and Prometheus for logs and metrics through their respective `loki.write` and `prometheus.remote_write`. I assume it's mostly a matter of changing it so the OTel receiver and the processors pass through metrics and logs to eventually `otelcol.exporter.otlp.<name>.input`, and have `loki.source.*` and `prometheus.scrape.*` `forward_to` into the memory processor. Having a complete example in the docs would be great.

**Comment by proffalken** [comment]
https://gist.github.com/proffalken/ac9933d92c92432bae6be4bf705a302e has two examples configs, one for storing the Auth details in the config file, the second shows how to retrieve them from hashicorp vault using the new Vault integration.

I'll try to get something like this into the docs next week.

**Comment by proffalken** [comment]
Mea culpa, I completely forgot about this.

I'll try and get to this soon.
