### ISSUE TITLE
Alloy 1.4.0/1.3.3: Quoting issues with Windows Service

### ISSUE THREAD

**Issue by jkroepke** [grafana/alloy#1764]
### What's wrong?

On a default installation, The ServicePath in the Windows Registry is quoted. Introduced in https://github.com/grafana/alloy/pull/1694

![Image](https://github.com/user-attachments/assets/fc7ec49c-5c36-41ae-9640-e70147c85c11)

The  registry value is passed to the go exec.ContextCommand function and leads to an issue (see logs below)

I have the feeling, that the command in not running in a shell context. Go thinks, the quotes are part of real path. Since it beginning with a quote, no absolute path is indicated and the current working dir is preprend.

The current workaround is remove the quotes inside the registry (HKLM:\SOFTWARE\GrafanaLabs\Alloy)

For record: I'm not talking about the quotes, with are living at the Windows Service Configuration. The alloy service binary starts well and read values from the registry. here is the issue.

### Steps to reproduce

1. Run the installer
2. Start the service

### System information

Windows Server 2016

### Software version

Grafana Alloy 1.4.0

### Configuration

N/A

### Logs

level=error msg="service exited with error" err="exec: \"\\\"C:\\\\Program Files\\\\GrafanaLabs\\\\Alloy\\\\\\\"C:\\\\Program Files\\\\GrafanaLabs\\\\Alloy\\\\alloy-windows-amd64.exe\\\"\": file does not exist" exit_code=-1

**Comment by Andrrews** [comment]
We reported the same issue with latest installation file.

**Comment by bmorvan-mphygiene** [comment]
I have the same issue on multiple servers with versions 1.3.3 and 1.4.0 on Windows 2016, 2019, and 2022.

Thanks @jkroepke for the workaround !
