### ISSUE TITLE
Cannot filter journal log lines from loki.source.journal with loki.process component

### ISSUE THREAD

**Issue by sergeykranga** [grafana/alloy#1776]
### What's wrong?

Dropping specific lines from `loki.source.journal` matching a `stage.drop` stage from `loki.process` component does not have any effect and all journal logs are sent.

### Steps to reproduce

Given the provided configuration, I would expect no logs in Loki, yet all logs are sent. Changing `expression` to any other value also produces the same result.

### System information

Linux 5.10.225-213.878.amzn2.x86_64

### Software version

Grafana Alloy v1.4.0

### Configuration
```
loki.source.journal "logs" {
  path = "/var/log/journal"
  relabel_rules = discovery.relabel.journal.rules
  forward_to = [loki.process.journal.receiver]
}

discovery.relabel "journal" {
  targets = []

  rule {
    source_labels = ["__journal__transport"]
    action = "keep"
    regex = "kernel"
  }

  rule {
    source_labels = ["__journal__hostname"]
    target_label  = "instance"
  }
}

loki.process "journal" {
  stage.drop {
    expression = ".*"
  }

  forward_to = [loki.write.default.receiver]
}

loki.write "default" {
  endpoint {
    url = "http://loki:3100/loki/api/v1/push"
  }
}
```

**Comment by ptodev** [comment]
Hi @sergeykranga, are you sure that you are using this config? Could you be looking at old logs on Loki? When I use this config, I see journald logs:
```
loki.source.journal "logs" {
  forward_to = [loki.echo.default.receiver]
}

loki.echo "default" {}
```

When I switch to this one, I no longer see logs:
```
loki.source.journal "logs" {
  forward_to = [loki.process.journal.receiver]
}

loki.process "journal" {
  stage.drop {
    expression = ".*"
  }

  forward_to = [loki.echo.default.receiver]
}

loki.echo "default" {}
```

I also see from the metrics that the logs were dropped due to loki.process:
```
# HELP loki_process_dropped_lines_total A count of all log lines dropped as a result of a pipeline stage
# TYPE loki_process_dropped_lines_total counter
loki_process_dropped_lines_total{component_id="loki.process.journal",component_path="/",reason="drop_stage"} 27
```
