### ISSUE TITLE
discovery.kubelet doesn't work on GKE Autopilot

### ISSUE THREAD

**Issue by artem-zherdiev-ingio** [grafana/alloy#1808]
### What's wrong?

Hi, while trying to migrate to Grafana Alloy as one solution, we found that Kubelet doesn't work for GKE Autopilot because of usage /pods that require nodes/proxy, which is not allowed on Autopilot.

User "system:serviceaccount:NS:SA" cannot get resource "nodes/proxy" in API group "" at the cluster scope: **GKE Warden authz [denied by managed-namespaces-limitation**]: cluster scoped resource "nodes/proxy" is managed and access is denied"

The only one solution which works for us now is OpenTelemetry kubeletstatsreceiver which, how I see, [uses /stats/summary](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/scraper.go#L101) under the hood and then create metrics based on it.

GKE Documentation says that it's not recommended to use [nodes/proxy](https://cloud.google.com/kubernetes-engine/docs/how-to/disable-kubelet-readonly-port) either autopilot or standard. 

> If your workload uses the /pods endpoint on the insecure kubelet read-only port, you need to grant the nodes/proxy RBAC permission to access the endpoint on the secure kubelet port. nodes/proxy is a powerful permission that you can't grant in GKE Autopilot clusters and that you shouldn't grant in GKE Standard clusters. Use the Kubernetes API with a [fieldSelector](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) for the node name instead.

Do you plan to make this module work on Autopilot as well?

### Steps to reproduce

1. Deploy Alloy on GKE Autopilot
2. Enable discovery.kubelet
3. See Forbidden in logs 
 

### System information

GKE Autopilot v1.29.5 ~ v1.30.3

### Software version

Grafana Alloy v1.4.1 / Helm Chart 0.9.0

### Configuration

```
discovery.kubelet "default" {
  bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  tls_config {
    ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  }
  url = string.format("https://%s:%d", sys.env("K8S_HOST_IP"), 10250)
  refresh_interval = "30s"
}
```

**Comment by artem-zherdiev-ingio** [comment]
This example helps me understand how it works. https://github.com/grafana/alloy/issues/452#issuecomment-2260218491

**Comment by nasielgarcia** [comment]
Hi @artem-zherdiev-ingio ,  

Were you able to fix the issue or find any workaround?  
I'm stuck with the same problem and could really use some help.  

Cheers!

**Comment by artem-zherdiev-ingio** [comment]
@nasielgarcia Hi, yes, I am using such config on alloy in daemonset mode. It connects to cadvisor metrics on node kubelet.
```
prometheus.scrape "cadvisor" {
  forward_to        = [prometheus.relabel.cadvisor.receiver] // or your metric receiver

  scrape_interval = "30s"
  job_name = "cadvisor"
  targets  = [{
    "__address__" = string.format("%s:%d", sys.env("K8S_HOST_IP"), 10250),
    "__metrics_path__" = "/metrics/cadvisor",
    "instance" = sys.env("HOSTNAME"),
  }]
  scheme   = "https"

  tls_config {
    server_name          = sys.env("K8S_HOST_IP")
    ca_file              = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    insecure_skip_verify = false
  }

  bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"

}
```

**Comment by nasielgarcia** [comment]
Hi @artem-zherdiev-ingio

Thank you so much for your help; it worked perfectly for me! I was having trouble using the ServiceMonitor approach with a kubelet pointing service as the "entry point," like the Grafana Agent Operator and Prometheus Operator use. Even though the documentation said switching from Grafana Agent to Alloy should be easy, it didn’t work for me.

Thanks a lot again.
Have a nice one!
