### ISSUE TITLE
Alloy Component to Replace prometheus http_sd_config

### ISSUE THREAD

**Issue by dfercode** [grafana/alloy#1866]
### Request

how can transform prometheus http_sd_config to alloy config? is there existing alloy componet to do this?

### Use case

migrate prometheus http_sd_config to alloy

**Comment by ptodev** [comment]
Hi, you could use [discovery.http](https://grafana.com/docs/alloy/latest/reference/components/discovery/discovery.http/). For more information on migrating from Prometheus, please see the [Migrate from Prometheus to Grafana Alloy](https://grafana.com/docs/alloy/latest/set-up/migrate/from-prometheus/) doc.
