### ISSUE TITLE
add proxy_url to otelcol.exporter.otlp components

### ISSUE THREAD

**Issue by steventill** [grafana/alloy#1892]
### Request

the otelcol.exporter.otlp & otelcol.exporter.otlphttp components do not have an individual proxy option.  it appears that it is an undocumented feature https://github.com/open-telemetry/opentelemetry-java/issues/6204

i was expecting something similar to the prometheus.remote_write client block. where you would do something like this:

`otelcol.exporter.otlp "default" {
  client {
    endpoint="https://otlp.grafana.net"
    proxy_url="http://internal.proxy.com:1234"
    auth=otel.auth.basic.default
  }
}
otelcol.auth.basic "default" {
  user="username"
  password="password"
}
`

### Use case

the only way to do this now is to set as an extraEnv the HTTPS_PROXY, this is really unclear, adding this to the block would clean it up, and make it easier to use proxies.  In addition, this would allow support for multiple proxies

**Comment by wildum** [comment]
I opened a PR to add the proxy_url to the otlphttp exporter. I think that this attribute is not available in the upstream component for grpc
