### ISSUE TITLE
APT repository returns 404

### ISSUE THREAD

**Issue by Novakov** [grafana/alloy#190]
### What's wrong?

Installing Grafana Agent flow using Grafana's APT repository fails with 404 error. Seems like the same situation as last week: https://github.com/grafana/agent/issues/6826

### Steps to reproduce

1. Add Grafana's APT repository
2.  Try to install grafana-agent-flow

```
yyy@yyy:~$ sudo apt install -d grafana-agent=0.40.2-1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  grafana-agent
0 upgraded, 1 newly installed, 0 to remove and 38 not upgraded.
Need to get 118 MB of archives.
After this operation, 411 MB of additional disk space will be used.
Err:1 https://apt.grafana.com stable/main amd64 grafana-agent amd64 0.40.2-1
  404  Not Found [IP: 199.232.190.217 443]
E: Failed to fetch https://apt.grafana.com/pool/main/g/grafana-agent/grafana-agent-0.40.2-1.amd64.deb  404  Not Found [IP: 199.232.190.217 443]
```

**Comment by tpaschalis** [comment]
Thanks everyone for chiming in. We've had an issue with our pipeline publishing our release artifacts, but since then it's been fixed.

I'm closing this issue as resolved.
