### ISSUE TITLE
Add a configuration option to pyroscope.scrape to define for how long a CPU profile should run

### ISSUE THREAD

**Issue by julienvey** [grafana/alloy#195]
### Request

Right now, the only configuration option to customize scraping interval for CPU collection are `scrape_interval` and `delta`. If we want to use delta profiling, but reduce the amount of profiles we collect, there's no other options.

As the doc says 
> The seconds used will be equal to scrape_interval - 1. For example, if scrape_interval is "15s", seconds will be 14 seconds. If the HTTP endpoint is /debug/pprof/profile, then the HTTP query will become /debug/pprof/profile?seconds=14

- If we set a larger scrape interval (60s), `seconds` will be 59
- If we set a smaller scrape interval (15s), `seconds` will be 14

With this param, we are basically running profiles all the time (except for this 1s between profiles)

We could add a configuration option to let the user decide of this `seconds` value. 

for instance
```
scrape_interval = 15s
scrape_duration = 5s
```

would result in a call to `/debug/pprof/profile?seconds=5` every 15s. This would enable considerable savings on resources used by grafana-agent and pyroscope, if it's a tradeoff the user is willing to accept

### Use case

User might want to reduce the amount of CPU profiles collected in order to save on resources (CPU, network, storage...)

**Comment by hainenber** [comment]
@julienvey I've repeated the PR from the original one in `grafana/agent`. Finger crossed it'll get review and released! 🤞
