### ISSUE TITLE
The ability to split the configuration

### ISSUE THREAD

**Issue by orlovds** [grafana/alloy#1956]
### Request

Hello, 
need to be able to split the settings into different files, depending on the type or application. At startup, alloy collects a common config and works with it. How do you see it?

### Use case

I would like to maintain a configuration for monitoring and logging in different files.
For example, there are loki.alloy and mimir.alloy in the folder, with different types of settings

**Comment by Nachtfalkeaw** [comment]
In Windows registry add this to the "Arguments". All config files need to end with   .alloy   and then you can make multilple files.


```
run
C:\Program Files\GrafanaLabs\Alloy\all_my_allo_config_files\
--storage.path=C:\Program Files\GrafanaLabs\Alloy\data
--disable-reporting
--server.http.listen-addr=0.0.0.0:12345
--stability.level=experimental
--feature.community-components.enabled
```


and on linux it is in the command:

```
ExecStart=/opt/alloy/alloy run \
    --storage.path=/opt/alloy/ \
    --stability.level="experimental" \
    --disable-reporting \
    --feature.community-components.enabled \
    --server.http.listen-addr=":12345" \
    /opt/alloy/all_my_allo_config_files/
```

**Comment by orlovds** [comment]
@Nachtfalkeaw Very indirectly, why can't you explicitly write about it in relevant section of the documentation - https://grafana.com/docs/alloy/latest/get-started/configuration-syntax/files. 
It is clear that the word "files" is suggestive, but there is no necessary information.

**Comment by orlovds** [comment]
@Nachtfalkeaw thanks a lot for correct information!

**Comment by wildum** [comment]
> https://grafana.com/docs/alloy/latest/get-started/configuration-syntax/files.
It is clear that the word "files" is suggestive, but there is no necessary information.

Hi, this is documented in the run command: https://grafana.com/docs/alloy/latest/reference/cli/run/
