### ISSUE TITLE
Use the OTel DataDog receiver from upstream

### ISSUE THREAD

**Issue by ptodev** [grafana/alloy#1958]
### Request

Alloy has been using a [custom fork](https://github.com/grafana/alloy/tree/v1.4.3/internal/etc/datadogreceiver) of `otelcol.receiver.datadog`. According to @jesusvazquez, the [upstream version](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.111.0/receiver/datadogreceiver) is now stable enough for Alloy to use. We can delete the fork from the Alloy codebase and use upstream instead.

### Use case

Less code duplication.

**Comment by wildum** [comment]
This was done in https://github.com/grafana/alloy/pull/2012
