### ISSUE TITLE
Add a `stage.keep` to `loki.process`

### ISSUE THREAD

**Issue by Gladear** [grafana/alloy#1976]
### Request

`stage.drop` is nice, but sometimes, I would like to be able to keep only the logs matching a value or expression. As far as I know, this is not doable right now, or not easily, so we have to drop explicitly all the logs we do not want.

### Use case

My very own use case is related to Heroku. I have a log drain from my Heroku app to my Alloy instance, which works fine. The log drains logs a lot of data, some from the database, other from the app, or other from the "Heroku API" (start and stop of dynos for example). I don't want to process all these logs the same way, as they have different formatting and different values I want to extract, so I'm forwarding the logs from my Heroku source to 3 different `loki.process` components. Each of these components has to explicitly drop the logs they won't process. I think it would be much simpler to just "keep" the logs they know how to process.

Here's a simplified version of my `config.alloy` file.

```
loki.source.heroku "heroku_logs" {
  forward_to = [
    loki.process.heroku_provider_logs.receiver,
    loki.process.heroku_api_logs.receiver,
    loki.process.heroku_postgres_logs.receiver,
  ]
}

loki.process "heroku_provider_logs" {
  stage.drop {
    source = "__heroku_drain_app"
    value  = "app"
  }
  # I'd rather keep when `__heroku_drain_app="heroku"`
}

loki.process "heroku_provider_logs" {
  stage.drop {
    source = "__heroku_drain_app"
    value  = "heroku"
  }
  stage.drop {
    source = "__heroku_drain_proc"
    expression = "((web|worker|run|postgres)\\.\\d+)|heroku-postgres)"
  }
  # I'd rather keep when `__heroku_drain_app="app" and __heroku_drain_proc="api"`
}

loki.process "heroku_postgres_logs" {
  stage.drop {
    source = "__heroku_drain_app"
    value  = "heroku"
  }
  stage.drop {
    source = "__heroku_drain_proc"
    value  = "api"
  }
  stage.drop {
    source     = "__heroku_drain_proc"
    expression = "(web|worker|run)\\.\\d+"
  }
  # I'd rather keep when `__heroku_drain_app="app" and __heroku_drain_proc=~/(^postgres)|heroku-postgres/`
}
```

**Comment by Nachtfalkeaw** [comment]
Hello,

I think I have a similar situation.

I do a "loki.source.file" of /var/log/syslog or /var/log/messages.
In this file there are system logs and logs of specific applications.

However I want to forward logs of specific applications to specific loki tenants and drops the system logs and other application specific logs.

The reason for that is that we have people who ae responsible for the base system and do not care about the applications. Orthers are responsible for the application but not for the base system. shared responsibilities and for that reason shared logs / tenants.


I tries with "stage.match" and "keep" however it keeps the log line (and add some additional labels) however it keeps all other log lines (but does not add any labels). - I would expect it keeps only what matches and drops the rest.

```
stage.match {
    selector = "{service_name=~\".+\"} |~ \"tempo\""
    action   = "keep"

    drop_counter_reason = "not tempo"
	
    stage.static_labels {
       values = {
         service_name_sub1 = "sub1_tempo",
         service_name_sub2 = "sub2_syslog_tempo",
       }
    }
}
```

**Comment by Gladear** [comment]
Indeed, it looks like `stage.match` is a better way to solve this. I did refactor my code to use it, too, and it works perfectly fine 👌
Thanks for the feedback 😄
