### ISSUE TITLE
otelcol.processor.attributes delete pattern not working?

### ISSUE THREAD

**Issue by fede843** [grafana/alloy#2000]
### What's wrong?

I am trying to delete an attribute based on a patter.
The pattern is totally ignored. No matter what I set, it always delete the attribute or not based on the key matching.

Even more, docs says:

> delete: Deletes an attribute from the input data.
> The key attribute and/or the pattern attribute is required. It specifies the attribute to act upon.

Well, if I set only a pattern, I get an error that key is missing.

Not sure if the error is introduced in Alloy or if comes from upstream OTEL Collector.

### Steps to reproduce

You can try to remove any attribute, for instance the http.method

    action {
	key="http.method"
        pattern= `GET`
        action = "delete"
    }

Regardless what you set or not in pattern, it always deletes the attribute.

### System information

Docker

### Software version

Alloy 1.4.3

**Comment by wildum** [comment]
Hello, thanks for reporting this, it's indeed a bug! Alloy assumes that the key is always required but it should only be required for the actions insert, update, and upsert. For the action `delete`, only `key`, only `pattern`, and both `key/pattern` should be supported.

**Comment by wildum** [comment]
solved by https://github.com/grafana/alloy/pull/2124
