### ISSUE TITLE
Make the prometheus operator informer sync timeout configurable and increse the default

### ISSUE THREAD

**Issue by thampiotr** [grafana/alloy#2004]
### Request

The timeout defined here:

https://github.com/grafana/alloy/blob/main/internal/component/prometheus/operator/common/crdmanager.go#L41

should ideally be configurable. A larger default timeout could also make sense, because this happens at component `Run` and could result in a failed component. Sometimes the request takes too long.

### Use case

For large / slow clusters

**Comment by DWebb0** [comment]
I'm registering my interest here. Form3 are exploring the Victoria Metrics agent as a workaround.
