### ISSUE TITLE
Installing grafana agent flow debian package on Ubuntu gives error

### ISSUE THREAD

**Issue by mshahzeb** [grafana/alloy#207]
### What's wrong?

Installing grafana agent debian package on Ubuntu gives the following error:
<img width="758" alt="image" src="https://github.com/grafana/agent/assets/17196882/bcedc58b-ce63-44b6-8b27-0b3f169e7872">

### Steps to reproduce

1. Download the latest flow debian package (arm64)
2. Install using `dpkg -i <deb>`

### System information

Ubuntu 22.04.1 LTS ARM64

### Software version

grafana-agent-flow-0.39.1-1.arm64.deb

### Logs

```text
shb@ubuntu2204-shb:/tmp$ sudo dpkg -i grafana-agent-flow-0.39.1-1.arm64.deb 
(Reading database ... 164908 files and directories currently installed.)
Preparing to unpack grafana-agent-flow-0.39.1-1.arm64.deb ...
Unpacking grafana-agent-flow (0.39.1-1) over (0.39.1-1) ...
Setting up grafana-agent-flow (0.39.1-1) ...
chown: cannot access '/var/lib/grafana-agent-flow': No such file or directory
dpkg: error processing package grafana-agent-flow (--install):
 installed grafana-agent-flow package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grafana-agent-flow
```
```

**Comment by rfratto** [comment]
Hi, I'm going to close this as stale for now since we were unable to reproduce it. If continue to experience this issue, feel free to open a new issue as we don't monitor closed issues for comments.
