### ISSUE TITLE
Alloy does not recognize "queue_config" block

### ISSUE THREAD

**Issue by hmahdiany** [grafana/alloy#2159]
### What's wrong?

I'm using Grafana Alloy version "1.4.3" running as a deamon-set on a Kubernetes cluster version 1.26.16. Here is my remote write configuration:
```
prometheus.remote_write "remote_write" {
        external_labels = {
        cluster = env("CLUSTER"),
        source_exporter = "alloy",
        }
        queue_config {
          max_samples_per_send = 8000
          batch_send_deadline  = "60s"
        }
        endpoint {
          url = env("REMOTE_WRITE_URL")
            basic_auth {
              username = env("REMOTE_WRITE_USERNAME")
              password = env("REMOTE_WRITE_PASSWORD")
            }
        }
      }
```

I get this error message:
```
Error: /etc/alloy/config.alloy:7:3: unrecognized block name "queue_config"

 6 |     }
 7 |     queue_config {
   |  ___^^^^^^^^^^^^^^
 8 | |     max_samples_per_send = 8000
 9 | |     batch_send_deadline  = "60s"
10 | |   }
   | |_^^^
11 |     endpoint {
interrupt received
Error: could not perform the initial load successfully
```

As documentation suggests "queue_config" should work from version "1.3.0" but it doesn't.

### Steps to reproduce

Deploy Grafana Alloy via it's Helm chart with following configuration for remote write:

```
alloy:
  configMap:
    # -- Create a new ConfigMap for the config file.
    create: true
    # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
    content: |
      prometheus.remote_write "remote_write" {
        external_labels = {
        cluster = env("CLUSTER"),
        source_exporter = "alloy",
        }
        queue_config {
          max_samples_per_send = 8000
          batch_send_deadline  = "60s"
        }
        endpoint {
          url = env("REMOTE_WRITE_URL")
            basic_auth {
              username = env("REMOTE_WRITE_USERNAME")
              password = env("REMOTE_WRITE_PASSWORD")
            }
        }
      }
```

It creates a configmap on your cluster called "alloy" and when you get Alloy log it shows that "queue_config" is not a valid block.

### System information

Kubernetes 1.26.16

### Software version

Grafana Alloy v1.4.3

### Configuration

```text
prometheus.remote_write "remote_write" {
        external_labels = {
        cluster = env("CLUSTER"),
        source_exporter = "alloy",
        }
        queue_config {
          max_samples_per_send = 8000
          batch_send_deadline  = "60s"
        }
        endpoint {
          url = env("REMOTE_WRITE_URL")
            basic_auth {
              username = env("REMOTE_WRITE_USERNAME")
              password = env("REMOTE_WRITE_PASSWORD")
            }
        }
      }
```

### Logs

```text
`Error: /etc/alloy/config.alloy:7:3: unrecognized block name "queue_config"

 6 |     }
 7 |     queue_config {
   |  ___^^^^^^^^^^^^^^
 8 | |     max_samples_per_send = 8000
 9 | |     batch_send_deadline  = "60s"
10 | |   }
   | |_^^^
11 |     endpoint {
interrupt received
Error: could not perform the initial load successfully`
```

**Comment by dehaansa** [comment]
The `queue_config` block belongs _inside_ the `endpoint` block, that should resolve your issue.

**Comment by hmahdiany** [comment]
Thank you @dehaansa. It definitely solved my problem. I think [this](https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/#queue_config-block)  document should be updated.

**Comment by wildum** [comment]
hi, the [blocks table](https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/#blocks) has a hierarchy column with "endpoint > queue_config".
"The > symbol indicates deeper levels of nesting. For example, endpoint > basic_auth refers to a basic_auth block defined inside an endpoint block."
This seems easy to miss in big docs though. Maybe nested block descriptions should mention their parent block? @clayton-cornell any thoughts on this?

**Comment by clayton-cornell** [comment]
I've got an open task/ToDo to work on clarifying the component docs. One of the points I want to work on is exactly this. I'm not sure what solution will help make this more obvious. The nesting and hierarchy is important and making it clear what belongs where...
