### ISSUE TITLE
Log bug? memory is not limited, skipping: %v

### ISSUE THREAD

**Issue by systemcrash** [grafana/alloy#2223]
### What's wrong?

This line looks wrong: `%v`?

alloy  | ts=2024-12-05T15:55:28.172162987Z level=info source=/go/pkg/mod/github.com/!kim!machine!gun/automemlimit@v0.6.0/memlimit/memlimit.go:170 msg="memory is not limited, skipping: %v" package=github.com/KimMachineGun/automemlimit/memlimit !BADKEY="memory is not limited"

### Steps to reproduce

Run alloy 1.5.1

### Software version

1.5.1

### Configuration

```text

```

### Logs

```text
alloy  | ts=2024-12-05T15:55:28.172162987Z level=info source=/go/pkg/mod/github.com/!kim!machine!gun/automemlimit@v0.6.0/memlimit/memlimit.go:170 msg="memory is not limited, skipping: %v" package=github.com/KimMachineGun/automemlimit/memlimit !BADKEY="memory is not limited"
```

**Comment by dehaansa** [comment]
Looks like this was resolved upstream, and we'll make sure to update the dependency to fix it.
https://github.com/KimMachineGun/automemlimit/pull/19
