### ISSUE TITLE
Add `otelcol.processor.groupbyattrs` component

### ISSUE THREAD

**Issue by ryanartecona** [grafana/alloy#224]
### Request

Add the OTEL module [groupbyattrsprocessor](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor#section-readme).

### Use case

I have an agent scraping prometheus metrics from a kubernetes kubelet, whose metrics I also pass through an `otelcol.processor.k8sattributes` step (and a `otelcol.processor.transform` to turn otel resource attributes to datapoint attributes, [as mentioned in the `otelcol.processor.k8sattributes` docs](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.processor.k8sattributes/#adding-kubernetes-metadata-to-prometheus-metrics)). What I want is basically what's stated in that doc section, to enrich the kubelet prometheus metrics (with labels like `pod="myapp-59fb8bb44d-6qfgf",namespace="default"`) with metadata that becomes extra labels (like `k8s_deployment_name="myapp"`). The pipeline looks like this:

```text
prometheus.scrape 
  -> otelcol.receiver.prometheus 
    -> otelcol.processor.k8sattributes 
      -> otelcol.processor.transform 
        -> otelcol.exporter.prometheus
```

However, with that pipeline, I get attributes from the k8sattributes processor that _don't match up_ with the labels reported by kubelet. For example, I'll get a datapoint with `namespace="default",k8s_namespace_name="kube-system"` (where `namespace` is from kubelet and `k8s_namespace_name` is from k8sattributes). Also, most datapoints seem "sticky" to particular label values, i.e. many pods across many namespaces will all get a `k8s_namespace_name="kube-system"` label.

What I believe is happening is that in the otel components, all the datapoints are associated with a single Resource for the single `prometheus.scrape` job. So, the k8sattributes step will talk to the Kubernetes API and update the otel Resource, but because the resource is shared, there are conflicts and eventually the last (or the first) write wins and all the other datapoints get those labels.

If that's what's happening, adding the `groupbyattrsprocessor` module should at least let me fix this pipeline so that the k8sattributes enrichment works as expected.

**Comment by kehindesalaam** [comment]
Hello @ptodev , could you please assign the issue to me?
