### ISSUE TITLE
Upgrade Alloy to Prometheus 2.50

### ISSUE THREAD

**Issue by ptodev** [grafana/alloy#227]
### Request

Upgrade Agent's go.mod file to the latest version of Prometheus - 2.50.

### Use case

- Keeping current with the latest Prometheus developments.
- Helps us to take advantage of the Prometheus changes implemented via grafana/agent#2406
- Helps us close grafana/agent#5905

**Comment by thampiotr** [comment]
With [this change](https://github.com/prometheus/prometheus/pull/13932) landing in Prometheus, one of the issues with global registration of OTEL flags will be addressed, so perhaps it's worth waiting for it to be released.
