### ISSUE TITLE
Document environment variables alongside relevant config

### ISSUE THREAD

**Issue by ptodev** [grafana/alloy#245]
### Request

There are various environment variables (mostly from Go) which can affect the Agent's behaviour. Currently, those are not documented anywhere. It would be nice to add them in a new section in the [Command-line interface docs](https://grafana.com/docs/agent/latest/flow/reference/cli/). Component reference docs such as [tls config block](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.http/#tls_config-block) can then point to relevant sections of that env var doc.

### Use case

For example:
* `GODEBUG=x509usefallbackroots=1` which was added in grafana/agent#6340
* `HTTP_PROXY`
* Other `GODEBUG` use cases
* Maybe there are other modules such as gRPC, which have their own env vars too?

**Comment by clayton-cornell** [comment]
@ptodev Where can I find the env vars we use?

**Comment by ptodev** [comment]
There isn't an easy way to find them. Unlike cmd args, env vars could be referenced anywhere in the code, including in libraries which we import. This is what makes having a doc page important :) 

It's not necessary to have an exhaustive list. The main goals are:
* Making a space in the documentation for env vars, so that we know where to document them as time goes on.
* Documenting the most important ones (which are probably the ones listed in this issue).

**Comment by clayton-cornell** [comment]
GODEBUG env vars here: https://pkg.go.dev/runtime?utm_source=godoc#hdr-Environment_Variab
