### ISSUE TITLE
OtelCol exporters should should only initialise for the telemetry types for which they're configured

### ISSUE THREAD

**Issue by ptodev** [grafana/alloy#251]
### Request

If a River config file contains an `otelcol.exporter` such as `otelcol.exporter.otlp`, that exporter will always create the underlying Collector exporters for logs, metrics, and traces. For example, even if that exporter is only used for logs, it will still create the exporters for metrics and traces. The relevant code is in [component/otelcol/exporter/exporter.go](https://github.com/grafana/agent/blob/main/component/otelcol/exporter/exporter.go).

The code needs to be changed in such a way so that the component only starts the exporters which it is used for. For example, if only logs are forwarded to the exporter component, only the logs exporter should be created.

Maybe one way to solve this is to create lazy implementations of the interfaces of exporter.Traces, exporter.Metrics and exporter.Logs. Those lazy implementations would call functions like `e.factory.CreateTracesExporter` only when the `Start` function is called. Then have the code in `component/otelcol/exporter/exporter.go` use those lazy exporters instead of the result of `e.factory.CreateTracesExporter` directly. I'm not 100% sure whether this would work, but it's the most obvious approach that I can think of.

### Use case

This change is necessary in order to support the [load balancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.87.0/exporter/loadbalancingexporter) with metrics. The configuration for metrics is quite unique, and `otelcol.exporter.loadbalancing` can crash if it is configured to process a routing key of "trace ID" with a metrics exporter.

Related to grafana/agent#5684

**Comment by madaraszg-tulip** [comment]
https://github.com/grafana/alloy/pull/2242 may fix this issue. Only exporters supported by `routing_key` are created, and experimental metrics support is added.

**Comment by ptodev** [comment]
Closing this since we could use #2242 as a baseline for how we handle such cases in the future. Thank you, @madaraszg-tulip!
