### ISSUE TITLE
Error parsing syslog stream UDP

### ISSUE THREAD

**Issue by rbenea** [grafana/alloy#305]
### What's wrong?

I have updated to grafana-agent-flow-0.38.0-rc.0-1.amd64.deb in order to have syslog via UDP working. This was fixed in https://github.com/grafana/agent/issues/5197

For the moment we are sending syslog messages from PFSense, Mikrotik and Unifi devices.

From Mikrotik and Unify devices we get the message in journald:
`msg="error parsing syslog stream" component=loki.source.syslog.syslog err="expecting a version value in the range 1-999 [col 4]"`

From PFSense we get the message:
`msg="error parsing syslog stream" component=loki.source.syslog.syslog err="expecting a version value in the range 1-999 [col 5]`

### Steps to reproduce

Install grafana-agent-flow-0.38.0-rc.0-1.amd64.deb on a Debian12 VM with the config below and send remote syslog messages to the agent via UDP.

### System information

Debian 12.2 x86_64 Linux

### Software version

Grafana Agent 0.38.0-rc.0

### Configuration

```text
loki.relabel "syslog" {
  forward_to = []

  rule {
    source_labels = ["__syslog_message_hostname"]
    target_label  = "host"
  }
}
loki.source.syslog "syslog" {
  listener {
    address  = "0.0.0.0:5514"
    protocol = "tcp"
    labels   = { component = "loki.source.syslog", protocol = "tcp"}
  }

  listener {
    address  = "0.0.0.0:5514"
    protocol = "udp"
    labels   = { component = "loki.source.syslog", protocol = "udp"}
    use_rfc5424_message = true
  }

  relabel_rules = loki.relabel.syslog.rules
  forward_to = [loki.write.local.receiver]
}

loki.write "local" {
    endpoint {
        url = "http://127.0.0.1:3100/loki/api/v1/push"
    }
    external_labels = {}
}
```

### Logs

```text
Nov 17 15:26:07 logserver grafana-agent-flow[1308]: ts=2023-11-17T13:26:07.294962163Z level=warn msg="error parsing syslog stream" component=loki.source.syslog.syslog err="expecting a version value in the range 1-999 [col 4]"
Nov 17 15:30:08 logserver grafana-agent-flow[1308]: ts=2023-11-17T13:30:08.800809677Z level=warn msg="error parsing syslog stream" component=loki.source.syslog.syslog err="expecting a version value in the range 1-999 [col 5]"
```

**Comment by rarrr** [comment]
Any update on this?  I need to ingest a large amount of RFC3164 logs and Alloy just isn't capable of this.

**Comment by catap** [comment]
@rarrr I've made a PR for Loki to support such things, see: https://github.com/grafana/loki/pull/12810

**Comment by sushain97** [comment]
Great to see the progress here!

@catap are you planning to propagate your change to alloy?

It seems like it would boil down to upgrading https://github.com/grafana/alloy/blob/main/go.mod#L89?

**Comment by catap** [comment]
@sushain97 I can put it into my todo list but I have no promises when. Frankly speaking changes inside alloy should be quite trivial. Just integration of new version and some options to enable.

**Comment by sushain97** [comment]
@catap opened https://github.com/grafana/alloy/pull/1556 based on your changes!

**Comment by catap** [comment]
> @catap opened #1556 based on your changes!

You’re much faster than me!

**Comment by vladimir-benc** [comment]
I see this change doesn't squeeze into v1.4.3 . Will it be included in the next release ?

**Comment by wildum** [comment]
Hello, yes it will be part of v1.5 which is planned for the end of next week
