### ISSUE TITLE
GDPR: Disable grafana agent analytics by default and make them OPT-IN only.

### ISSUE THREAD

**Issue by Sommerwiesel** [grafana/alloy#317]
### Background

The grafana agent sends analytics to stats.grafana.org by default. This is neither documented in the installation site of the grafana cloud nor is this a good practise according to the gdpr.
Moreover, this behaviour cannot be disabled in the config file and requires a start parameter to be set.
This, on 90%+ of all Linux systems, requires a systemd unit overwrite, something that should be the last resort.
Overall, this is a bad practise that should be changed asap.

### Proposal

Change the default of grafana agent to not send any kind of analytics.
Make the setting OPT-IN via config file.

**Comment by mattdurham** [comment]
Closing this since it looks like it is resolved.
