### ISSUE TITLE
Agents Logs are not forwarded to Loki, if Agent can't start

### ISSUE THREAD

**Issue by jkroepke** [grafana/alloy#318]
### Request

The agent allows to send all the logs to an Loki endpoint. Is the possible, with an logging block and loki.write component.
However in case that the Agent fails to load remote module (http errors; syntax errors), the Agent fatal error cant be send to Loki. 

From my point of view, the root cause here is that logging and loki module are part of the runtime flow config. If the flow config can't be load, the Agent can't be send.

One idea to solve the problem would be to split the agent related config and the main config. Then, the agent config which contains the logging block + loki components can be loaded first, errors around the main configs could be sent to Remote Loki, too.

An alternative approch would be CLI arguments that logging should be delivered to Loki from beginning

### Use case

Better remote debugging capabilities.

**Comment by jkroepke** [comment]
Hi,

is this still in mind? Remote debugging is really hard at the moment, if the agent can't this own logs. We have always login into degraded machines and logging into the local logs.

**Comment by rfratto** [comment]
Hey @jkroepke, sorry for the radio silence. This is something I still think is an interesting idea, but it hasn't been formally proposed or approved yet, and after approval it's something that I'm not sure we'll have time to implement ourselves any time soon. 

If we're looking to move this forward, I think the next step would be for someone to create a short [proposal](https://github.com/grafana/alloy/tree/main/docs/design) for the desired behaviour that would fix this issue and then we can go from there.

**Comment by jkroepke** [comment]
A proposal doesn't need a [technical] solution, correct?

**Comment by rfratto** [comment]
Not always. In this case I don't think it needs any technical detail at all; just enough high-level detail to think through the implication for users.

**Comment by jkroepke** [comment]
Proposal: https://github.com/grafana/alloy/issues/1786
