### ISSUE TITLE
Proposal: Introduce submodule Component

### ISSUE THREAD

**Issue by bentonam** [grafana/alloy#339]
### Background

When using a module approach, whether it is `module.git`, `module.http`, or `module.file` if the module being referenced has references to other modules, the entire configuration has to be passed to the module so it can be used again.  Think of `module.git` if my main `agent-logs.river` includes a module i.e. 

```js
module.git "logs_primary" {
  repository = "https://github.com/grafana/agent-modules.git"
  revision = "main"
  path = "modules/kubernetes/logs/all.river"

  arguments {
    forward_to = [loki.write.default.receiver]
    git_repo = coalesce(env("GIT_REPO"), "https://github.com/grafana/agent-modules.git")
    git_rev = coalesce(env("GIT_REV"), "main")
    git_pull_freq = "5m"
  }
}
```

That has 40+ modules called from within it.  If a user wanted to use those modules from within their own hosted git environment, that used authentication for git clones, they would have to fork/copy the modules, then update each one of them to add the block 

```js
basic_auth {
  username = "XXXXXXXX"
  password = "XXXXXXXX"
}
``` 

This is counterintuitive to the module approach, they should be able to be re-used with no-changes.  

### Proposal

Introduce the concept of a submodule, where when a module is instantiated any further module calls will automatically use the same credentials that the parent module was instantiated with: 

If this is the module: 

```js
module.git "logs_primary" {
  repository = "https://github.com/grafana/agent-modules.git"
  revision = "main"
  path = "modules/kubernetes/logs/all.river"

  arguments {
    forward_to = [loki.write.default.receiver]
    git_repo = coalesce(env("GIT_REPO"), "https://github.com/grafana/agent-modules.git")
    git_rev = coalesce(env("GIT_REV"), "main")
    git_pull_freq = "5m"
  }
}
```

For example this calls a module for log targets that is currently defined as: 

```js
module.git "log_targets" {
  repository = argument.git_repo.value
  revision = argument.git_rev.value
  pull_frequency = argument.git_pull_freq.value
  path = "modules/kubernetes/logs/targets/logs-from-worker.river"

  arguments {
    forward_to = [module.git.log_formats_all.exports.process.receiver]
    tenant = argument.tenant.value
    git_repo = argument.git_repo.value
    git_rev = argument.git_rev.value
    git_pull_freq = argument.git_pull_freq.value
  }
}
```

This would change to be: 

```js
module.submodule "log_targets" {
  path = "modules/kubernetes/logs/targets/logs-from-worker.river"

  arguments {
    forward_to = [module.git.log_formats_all.exports.process.receiver]
    tenant = argument.tenant.value
  }
}
```

**Comment by thampiotr** [comment]
Closing this as obsolete, as the modules (which were experimental feature) have been changed quite dramatically since this was opened. The docs for new modules can be found here: https://grafana.com/docs/alloy/next/concepts/modules/
