### ISSUE TITLE
Adopt the Release life cycle for Grafana Labs in place of Agent's bespoke Stability guide

### ISSUE THREAD

**Issue by ptodev** [grafana/alloy#351]
### Background

The [Release life cycle for Grafana Labs](https://grafana.com/docs/release-life-cycle/) is meant to apply to all Grafana products. However, the Agent has its own [Stability guide](https://grafana.com/docs/agent/latest/stability/). We should consider adopting the Grafana company-wide approach.

### Proposal

Better consistency with other Grafana products. This may be beneficial to users who have already decided how they will adopt Grafana products in their organisation according to the official "Release life cycle for Grafana Labs".

**This is ideally something which should be done in a pre-1.0 version of the Agent.**

**Comment by thampiotr** [comment]
I believe that we already refer to Grafana Labs lifecycle, for[ example here ](https://grafana.com/docs/alloy/latest/reference/components/otelcol.receiver.vcenter/) and we no longer have a bespoke stability guide. I'm closing this as Declined as Obsolete, LMK if that's a mistake.
