### ISSUE TITLE
tail_sampling fails on traces larger than 4Mb

### ISSUE THREAD

**Issue by serhij-matvejev** [grafana/alloy#481]
Hi,

We have an issue with `tail_sampling` when the trace is larger than 4Mb. The grafana-agent supports traces larger than (default) 4Mb. The limit could be changed via the agent arguments (`-server.grpc.max-recv-msg-size-bytes` and `-server.grpc.max-send-msg-size-bytes`) and it works good when you just send traces _app -> agent -> tempo_.

But once you enable `tail_sampling` and send any trace larger than (default) 4Mb - it fails. The error message looks so:
```
ts=2023-03-01T09:44:56.763536564Z caller=zapadapter.go:84 level=error component=traces traces_config=default kind=exporter data_type=traces name=otlp/0 msg="Exporting failed. The error is not retryable. Dropping data." error="Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4194693 vs. 4194304)" dropped_items=1
```
So it drops the trace and it will not go through the agent to the tempo.

With smaller traces `tail_sampling` works good.

We have tested it on agent versions: `v0.28.1`, `v0.31.3` and `v0.32.0`. With `static` mode.

Probably it is possible to adjust the code and use non-default value (take it from `MaxRecvMsgSize` and `MaxSendMsgSize` if possible).

**Comment by clayton-cornell** [comment]
Updating to Alloy - places in the Alloy docs we reference `tail_sampling`:

* https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.tail_sampling/
* https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.exporter.loadbalancing

**Comment by clayton-cornell** [comment]
Discussing with the dev team:

The tail sampling size defaults to 4Mib. This can be adjusted with the `max_recv_msg_size` argument in the `otelcol.receiver.otlp` grpc block. Refer to the docs here: https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.receiver.otlp/#grpc-block

Closing this issue.
