### ISSUE TITLE
otelcol.receiver.prometheus: add support for native Prometheus histograms

### ISSUE THREAD

**Issue by rfratto** [grafana/alloy#483]
Add support for Prometheus native histograms (also called exponential histograms, sparse histograms) into `otelcol.receiver.prometheus`.

**Comment by wildum** [comment]
The support for native prometheus histograms was added to opentelemetry collector contrib with v0.99: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/13fca794d57a15e68b41b95ea8df64ff7564f04d
