### ISSUE TITLE
Split configuration files

### ISSUE THREAD

**Issue by 314eter** [grafana/alloy#572]
### Request

It would be nice to be able to split the configuration over multiple files in `/etc/alloy/config.d/*.alloy`.

An alternative would be to add an import statement (but not just for custom components) that accepts wildcards.

### Use case

We want to use the same base configuration on all our servers, but depending on which services are installed, different components should be added. Currently we have to let ansible generate the configuration file based on a single template that enables certain parts conditionally. Splitting the components over multiple files and letting each service install its own configuration file would be a lot easier.

**Comment by tpaschalis** [comment]
Hey Peter 👋 Thanks for opening an issue! (Also, love that profile pic 😅)

If I understand correctly what you're proposing, this is already available; the [run](https://grafana.com/docs/alloy/latest/reference/cli/run/) command accepts a directory that will concatenate all found `*.alloy` files and run them as a single config file. However you must make sure that component names are unique and that config blocks (such as `logging` or `import.*` are not repeated to avoid conflicts.

**Comment by 314eter** [comment]
Thanks for the quick reply. That indeed solves our issue.
