### ISSUE TITLE
Add automatically setting go memory limit if cgroup is available

### ISSUE THREAD

**Issue by mattdurham** [grafana/alloy#651]
### Request

Automatically set the gomemlimit if cgroup is set

### Use case

Allow memory to be limited without manually setting gomemlimit

**Comment by grcevski** [comment]
I was wondering if we could resurrect this. I was at a customer call and they were getting OOMs which were easily resolved once they setup GOMEMLIMIT. We are planning to do something for this for Beyla as well.

**Comment by mattdurham** [comment]
This was checked in for a while and moved to GA in October in 1.5.0.

**Comment by grcevski** [comment]
OK, interesting, then I need to find out what version of Alloy did they use and if it's 1.5.0 why didn't it work...

**Comment by grcevski** [comment]
OK, confirmed with the customer they are using 1.4.2 which is what's deployed with k8s monitoring.
