### ISSUE TITLE
Unable to scrape default Istio proxy metrics

### ISSUE THREAD

**Issue by SatyKrish** [grafana/alloy#671]
### What's wrong?

prometheus.scrape with auto-discovered pods as targets is not scraping Istio proxy metrics.

### Steps to reproduce

Istio prometheus-merge features exposes proxy metrics at `/stat/Prometheus` path.

prometheus.scrape has default metrics path as `/metrics`. It doesn’t respect the path specified in `prometheus.io/path` annotation.

### System information

kubernetes 1.18

### Software version

Grafana Alloy v1.0

**Comment by ptodev** [comment]
Hello, I think this is the sort of thing that the `prometheus.operator` [components](https://grafana.com/docs/alloy/latest/reference/components/) are used for. I'm not very familiar with those, but maybe @captncraig can opine and we can also clarify this in the docs.

**Comment by tpaschalis** [comment]
To dynamically set the path being scraped by specific targets, you might need to add some relabeling rules to get the prometheus.io/path annotations added as the `__metrics_path__` label.

**Comment by SatyKrish** [comment]
@tpaschalis most of our application namespaces are injected with Istio-proxy. Does it mean I need a separate scrape job for Istio monitored namespaces?

This works ootb with Prometheus agent, however while migrating to Grafana Alloy, Istio metrics stopped collecting.

**Comment by rfratto** [comment]
> This works ootb with Prometheus agent, however while migrating to Grafana Alloy, Istio metrics stopped collecting.

Hey there, I'm not aware of any feature in Prometheus Agent that natively understands the `prometheus.io/scrape` annotation. Can you share the Prometheus Agent config you were using?

**Comment by SatyKrish** [comment]
Prometheus helm chart default scrape config includes `relable_configs` for custom metric path.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1140

Is there a sample alloy config for achieving the same?

**Comment by rfratto** [comment]
Yes:

```
discovery.kubernetes "kubernetes_pods_slow" {
  role = "pod" 
}

discovery.relabel "kubernetes_pods_slow" {
  targets = discovery.kubernetes.kubernetes_pods_slow.targets 

  // ... other rules ... 

  rule {
    source_labels = ["__meta_kubernetes_pod_annotation_prometheus_io_path"]
    target_label  = "__metrics_path__"
    regex         = "(.+)"
    action        = "replace"
  }


  // ... other rules ... 
}

prometheus.scrape "kubernetes_pods_slow" {
  targets         = discovery.relabel.kubernetes_pods_slow.output 
  scrape_interval = "5m"
  scrape_timeout  = "30s"
  honor_labels    = true 
   
  forward_to = RECEIVER_LIST 
}
```

This example isn't complete, `RECIEVER_LIST` would need to be replaced with the set of components to send scraped metrics to, and it's missing the other rules from the Helm chart you linked to, but this would be the general pattern to use.

**Comment by SatyKrish** [comment]
@rfratto , thanks for your inputs and directions. I took reference of kubernetes annotations alloy module to add necessary relabel configs. Now able to see Istio metrics.

As a next step will use the modules for defining alloy config.

**Comment by SatyKrish** [comment]
Components used to get this working

- `discovery.kubernetes` to discover pods 
- `discovery.relabel` to replace metrics_path
- `prometheus.scrape` to scrape the pods 
- `prometheus.remote_write` to push metrics to mimit
