### ISSUE TITLE
No error logs when the HTTP server cannot start

### ISSUE THREAD

**Issue by rfratto** [grafana/alloy#694]
### What's wrong?

If the HTTP server cannot start (such as the listen address is already in-use by another process), the HTTP server fails silently and doesn't generate any error-level logs.

This is related to #364, but slightly more specific, as the user has no signal that anything went wrong, other than self-scraping and scraping exporter components fail.  

Note that the HTTP service [does return an error](https://github.com/grafana/alloy/blob/c6f4f3054b9f5032ee8d38b1570bf451dfd58fd3/internal/service/http/http.go#L154), but this error [isn't logged](https://github.com/grafana/alloy/blob/c6f4f3054b9f5032ee8d38b1570bf451dfd58fd3/internal/alloy/internal/controller/scheduler.go#L140) anywhere. 

A reasonable fix here would be to change the code for the runnable scheduler to not ignore errors, or at least explicitly log errors before returning the error in the HTTP service.

### Steps to reproduce

1. Run two Alloy instances running listening on the same listen address.
2. Observe that the Alloy instance which started second does not have any log lines for `now listening for http traffic` nor any error indicating `failed to listen`. 

### Software version

v1.0.0

### Configuration

N/A 

### Logs

N/A (it's the lack of logs which is the problem 😛)

**Comment by mrashad10** [comment]
I've begun working on this and aim to deliver the code today.
