### ISSUE TITLE
Support Datadog exporter in Grafana Alloy

### ISSUE THREAD

**Issue by polyrain** [grafana/alloy#714]
### Request

Grafana Alloy wraps a lot of various Open Telemetry components, including some from the [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.96.0) repo (i.e. the Jaeger receiver).

This repo also has support for interacting with Datadog via OpenTelemetry, forming a [receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/datadogreceiver), [connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/datadogconnector), and [exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter). While it'd be great to one day have all of these, just the exporter is necessary to have Grafana Alloy interact with Datadog today. 

The exporter in v0.96.0 lacks full support for the HTTP Client settings, so if an upgrade to v0.99+ is in the near future for this repo then holding off is probably the right move as the configuration changed a bit here. 

I've started working on a wrapper for the exporter library, but the documentation recommends raising an issue first before going forward with larger bodies of work. 

### Use case

Part of working with larger organisations is supporting a variety of tools, and being able to maintain support for Datadog telemetry (mostly traces) via Alloy enables users to maintain flexibility and slowly move their telemetry collection towards OSS.

**Comment by wildum** [comment]
> The exporter in v0.96.0 lacks full support for the HTTP Client settings, so if an upgrade to v0.99+ is in the near future for this repo then holding off is probably the right move as the configuration changed a bit here.

FYI since v1.0.0 we committed to keep up with the Otel collector and update our dependency before every release. The update to v0.99 is currently WIP: https://github.com/grafana/alloy/pull/711

**Comment by polyrain** [comment]
> > The exporter in v0.96.0 lacks full support for the HTTP Client settings, so if an upgrade to v0.99+ is in the near future for this repo then holding off is probably the right move as the configuration changed a bit here.
> 
> FYI since v1.0.0 we committed to keep up with the Otel collector and update our dependency before every release. The update to v0.99 is currently WIP: https://github.com/grafana/alloy/pull/711

Ah, thanks for heads up! I'll pull those changes into my branch and add the full config support then. Cheers!

**Comment by polyrain** [comment]
> @polyrain any update on this issue?

@ezarko Mainly waiting for more comms from the maintainers, there was a discussion on the Grafana Slack around it. All I know right now is... stay tuned?

**Comment by wildum** [comment]
Hey, thanks for your patience, and sorry that it takes so much time, we spent some time discussing how we should approach vendor-specific components. We are moving forward with a concept of community components and the Datadog exporter will be the first candidate. I will open the PR for this concept this week and ping you on it @polyrain. Once this is merged to main we will be able to integrate this component

**Comment by wildum** [comment]
Hello @polyrain, we just introduced the new concept of "[Community components](https://github.com/grafana/alloy/pull/1001)" and we think that the Datadog exporter would be the perfect first candidate! Please have a look at the new doc. Would you like to be a maintainer for this component (you can step out at any time)?
You can carry on with the implementation. If you have any questions, please reach out :)

**Comment by polyrain** [comment]
> Hello @polyrain, we just introduced the new concept of "[Community components](https://github.com/grafana/alloy/pull/1001)" and we think that the Datadog exporter would be the perfect first candidate! Please have a look at the new doc. Would you like to be a maintainer for this component (you can step out at any time)?
> You can carry on with the implementation. If you have any questions, please reach out :)

Sure, I'm happy to do that. I'll update my PR this week once I get a chance to go over the new docs 👍

**Comment by ezarko** [comment]
@polyrain Any news on this front?

**Comment by polyrain** [comment]
> @polyrain Any news on this front?

@ezarko I've been super busy this week but I'll be addressing the PR feedback when I have a chance during this week :+1:

**Comment by ezarko** [comment]
@polyrain How have things been going? I hope that you have a little time to look at this soon.

**Comment by polyrain** [comment]
> @polyrain How have things been going? I hope that you have a little time to look at this soon.

I've been pretty busy, however I'm doing some development on this today.
