### ISSUE TITLE
Docs feedback: windows grafana alloy arugments

### ISSUE THREAD

**Issue by Kherm13** [grafana/alloy#719]
### URL

https://grafana.com/docs/alloy/latest/tasks/configure/configure-windows/

### Feedback

Trying to migrate from grafana agent static to grafana alloy and the Arguments section is lack luster. Not seeing anything in regards to passing the equivalent of

`-config.expand-env=true`

Am I missing something or does this not exist with Alloy / should I be doing it another way?

**Comment by rfratto** [comment]
Hi, `-config.expand-env=true` isn't necessary in Alloy because of [the env function](https://grafana.com/docs/alloy/latest/reference/stdlib/env/) always being available. 

For example:

```grafana-alloy
logging {
  level = env("LOG_LEVEL")
}
```

**Comment by Kherm13** [comment]
Makes sense and I was able to get what I wanted with this. Closing it out
