### ISSUE TITLE
Modules: support relative path

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#786]
### Background

The import.file block imports custom components from a file or a directory and exposes them to the importer. Users can specify the path to watch via the argument filename.

### Problem

The path is relative to the current working directory. This works fine when importing a module from the root config but it’s not ideal when the module itself has import.file blocks. Resolving the path relative to the module would be better in this case.

### Request

The following use-cases should be supported:

- import.file -> import.file
- import.git -> import.file
- import.string -> import.file

And if possible import.http -> import.file, but this one might be more tricky because it would only be possible if the nested import.file blocks would be turned into import.http blocks.

**Comment by thampiotr** [comment]
Should this become a proposal as it's a user-facing API?

**Comment by wildum** [comment]
There was already an accepted proposal for it: https://docs.google.com/document/d/16vRoiIxQVVlqqEGngm27Kcun6hF_BTpY2tPOSt05JWU/edit#heading=h.y9td4d74r21c
