### ISSUE TITLE
Alloy Clustering mode is currently incompatible with running inside an Istio mesh when deployed via the Helm Chart

### ISSUE THREAD

**Issue by josh-thisisbud** [grafana/alloy#800]
### What's wrong?

Currently this Alloy chart is falling into this trap when run with Istio as a sidecar - https://istio.io/latest/docs/ops/common-problems/network-issues/#503-error-while-accessing-headless-services

The fix is relatively simple, either; 

- Allow the end user to specify the port name used instead of hardcoding it to `http`. This will allow istio users to fallback to the TCP support which would work for this traffic.
- Alternatively, send a host header containing the hostname which was looked up on the request to join a cluster

### Steps to reproduce

Install Alloy via the helm chart on a Kubernetes cluster running Istio in strict mode and with allow_any traffic profile enabled. Have Alloy run with an istio sidecar. Attempt to turn on clustering mode. See that no nodes are able to communicate with each other.

### Software version

Alloy v1.0.0

**Comment by josh-thisisbud** [comment]
@rfratto As we use the published helm chart, how would I go about getting a new version cut with this fix in it? Is it done on a specific schedule? Could it already be done and I'm just not seeing it on [ArtifactHub](https://artifacthub.io/packages/helm/grafana/alloy)?

**Comment by rfratto** [comment]
@josh-thisisbud We don't have a normal release cadence for the Helm chart. We typically put out a release when enough changes accumulate. But since you're waiting for this change and I don't know of any alternatives to use a non-release version, I'll open a PR to release a new version now.

**Comment by josh-thisisbud** [comment]
Thank you!
