### ISSUE TITLE
Proposal: Alloy syntax conditionals

### ISSUE THREAD

**Issue by rfratto** [grafana/alloy#822]
### Background

Conditionals for the Alloy syntax were initially proposed by @tpaschalis on Dec 20, 2022 (#157).  

In Alloy's current state, conditionals would mainly reduce the need for a templating engine when deploying Alloy configs statically. While this is an interesting use case, it's difficult to justify over other priorities, as a templating engine can still be used. 

However, when considered alongside other proposals like #156, conditionals become a requirement for dynamic transformation and data routing, as acting on streams of data is not something that can be achieved with templating engines. Imagine a hypothetical `prometheus.route` component that can inspect incoming metrics and route to different components:

```grafana-alloy
prometheus.scrape "default" {
  targets    = ...
  forward_to = [prometheus.route.prod.receiver]
}

// prometheus.route inspects incoming metrics and uses their 
// labels to determine which component to forward them to. 
prometheus.route "prod" {
  forward_func = func(metric) => (
    if metric.namespace == "prod" then [prometheus.remote_write.prod.receiver]
    else if metric.namespace == "qa" then [prometheus.remote_write.qa.receiver]
    else [prometheus.remote_write.dev.receiver] 
  )
}

prometheus.remote_write "prod" { ... }
prometheus.remote_write "qa" { ... }
prometheus.remote_write "dev" { ... }
```

Even though conditionals are difficult to prioritize based on current functionality, adding support for conditionals now will allow us to build a framework for more advanced pipelines and set a precedence for how we can explore syntactical experiments using the `--stability.level` flag.   

This proposal supersedes #157. 

Please use reactions to vote on this proposal, with :+1: to signify support and :-1: to signify disapproval. When disapproving, a comment would be appreciated so we can discuss and refine the proposal as needed.

### Proposal

This proposal has the following goals:

* Enable conditionals within an Alloy _expression_. Conditional statements (such as a conditional block) is out of scope. 
* Balance readability and terseness for long chains of conditionals. 

#### Syntax 

Following the exploration in #157, the (ENBF) grammar for conditionals is as follows:

```
CondExpr      = "if" Expression "then" Expression [ CondElseExpr ] 
CondElseExpr  = "else" Expression

// CondExpr is a type of PrimaryExpr, giving it one of the lowest precedences.
PrimaryExpr = LiteralValue | ArrayExpr | ObjectExpr | CondExpr  
```

Here, the tokens `if`, `then`, and `else` are selected to align with natural language for how developers communicate conditionals. This makes conditionals slightly more approachable for non-developers compared to more obscure tokens like `?` and `:` and can aid in making conditionals easier to grok for first-time readers.    

While the `then` keyword is more verbose, it is easier to parse correctly as it strictly divides the "if" part of the expression with the value. 

Additionally, terminators are not required within the grammar for conditionals; this allows writers to place newlines arbitrarily for readability. 

Notably, "else if" is not found in the grammar as it is not necessary; an `else if` is identical to an else statement whose expression is another if statement. After parsing a CondExpr, the parser may choose to simplify chains of `else ifs` into a single AST element. 

CondExpr is parsed at the same levels as literals. This allows CondExpr to appear anywhere as part of an expression. In some cases this may hurt readability, such as adding the result of two conditionals together. The formatter will be responsible for producing a readable output; see the Style and Formatting section of this proposal for more information. 

The proposed grammar would parse all of these expressions:

```alloy-syntax
// Single if 
if CONDITION then VALUE 

// If/else 
if CONDITION then VALUE else VALUE 

// If/Else-if chain 
if CONDITION then VALUE 
else if CONDITION then VALUE  
else if CONDITION then VALUE 

// If/Else-if/Else 
if CONDITION then VALUE 
else if CONDITION then VALUE  
else if CONDITION then VALUE 
else VALUE  

// Alternative form for more readibility 
if CONDITION then 
  VALUE 
else if CONDITION then 
  VALUE 
else if CONDITION then 
  VALUE 
else 
  VALUE 
```

#### AST representation 

A new AST element will be added to represent conditionals. It will contain each branch of an `if` / `else if` / `else` chain produced by the parser. 

As there is no native concept for `else if` in the grammar, the parser is responsible for detecting `else if`s and flattening them out into a branch of the produced AST element. 

#### Evaluation 

The syntax evaluator will iterate through the conditionals within the expression and return the first value where the condition is `true`. If no conditions are `true`, the `else` value will be returned. If there is no `else` value, the expression evaluates to `null`. 

If a conditional in the overall expression is not a boolean value, the entire expression will fail to evaluate: 

```alloy-syntax
if a == 5 then 
  a * 2
else if 6 then // INVALID: expected 6 to be a boolean, got number 
  a * 3  
```

#### Delivery 

While it is unlikely support for conditionals will be removed, they should not be released immediately as Generally Available to give us time to iterate and explore the syntax, and potentially make breaking changes if needed. The initial delivery of conditionals will be tagged as _public preview_ and will require passing  `--stability.level=public-preview` or  `--stability.level=experimental` for conditional support.

If the stability level is not set properly, errors will be returned in three places:

* The scanner will return an error when encountering a token specific to conditionals (`if`, `else`, `then`). 
* Additionally, the parser will return an error if a conditional-specific token is scanned.
* Additionally, the syntax evaluator will return an error if  a conditional expression found in the AST. 

The bottom two conditions are technically unnecessary, but a defensive implementation is useful towards ensuring that users do not get access to a feature which is not GA yet. 

The `alloy fmt` command disables these checks to allow conditionals to be parsed and formatted regardless of whether the Alloy instance supports them. 

#### Alternatives considered 

Refer to #157 for alternative approaches that were considered. 

#### Acknowledgements

Credit to @tpaschalis for the work on the original proposal which formed the basis for this one.

**Comment by rfratto** [comment]
> Are user defined funcs a precursor to conditionals? Granted we can do them separately but I think they would have more limited use unless we defined func beforehand.

I touch on this in the proposal:

> Even though conditionals are difficult to prioritize based on current functionality, adding support for conditionals now will allow us to build a framework for more advanced pipelines and set a precedence for how we can explore syntactical experiments using the --stability.level flag.

**Comment by wildum** [comment]
Is nesting conditional statements not allowed?
`if CONDITION then if CONDITION then VALUE else VALUE end else if VALUE end `

**Comment by mattdurham** [comment]
Can we change the example to only use functionality that exists today + what you are suggesting? Might give the wrong direction on what this proposal enables.

**Comment by rfratto** [comment]
I believe it's important to acknowledge how conditions will be fundamental in the future. In total isolation I don't think we can prioritize them. This is a bit of a chicken and egg problem; if we do the more powerful stuff first it's hampered because conditionals don't exist, but conditionals on their own aren't extremely useful without the more powerful capabilities.

**Comment by mattdurham** [comment]
Do you think we should add an explicit return keyword? Thinking of if we implement variables, it might be helpful and clearer. In general approve of the idea and implementation.

**Comment by wildum** [comment]
You can already use custom components as variables. With conditionals this opens the door to many twisted scenarios 😄

**Comment by rfratto** [comment]
@wildum I expanded the grammar above to show the precedence of conditionals, and added a section for formatting to make it clear how the formatter will enhance readability. I'm going to resolve the earlier comments about nesting if expressions now :)

**Comment by rfratto** [comment]
I'm not dramatically opposed to curly brace syntax (though maybe whether the conditional needs to be wrapped in parenthesis is up for more debate).

While conditional blocks aren't in scope for this proposal, I believe they will quickly follow suit after conditional expressions are supported. Curly braces for conditional blocks may feel more natural with the curly brace

```
if env("ENVIRON") == "prod" {
  prometheus.remote_write "prod" {
    ...
  }
} 
```

as opposed to the current syntax:

```
if env("ENVIRON") == "prod" then
  prometheus.remote_write "prod" {
    ...
  }
end
```

If conditional blocks should use curly braces, that would influence whether conditional expressions should use curly braces as well. 

Overall, I think these are the tradeoffs of the curly brace syntax for expressions: 

* Pros:
  * Shares tokens with block statements and object literals; the only new tokens introduced would be `if` and `else`, compared to `if`, `else`, `then`, and `end`. 
  * Can be more familiar to programmers of declarative languages. 
  * Leads in more naturally to conditional blocks, where curly braces may feel more natural within the context of an Alloy config. 
* Cons:
  * As mentioned in the [original proposal](https://github.com/grafana/alloy/issues/157), curly braces may be confused with normal blocks when scanning the file.
  * Similarly to above, curly braces may make config authors think multiple statements can be placed inside the curly braces, but in reality only a single expression is valid. 
  * Can be less familiar to non-developers; `if a == 5 then "hello" else "goodbye"` can read similarly to English, whereas `if a == 5 { "hello" } else { "goodbye" }` might look more arcane to non-developers.

**Comment by mattdurham** [comment]
I am very slightly for the verbose `then end` since I think it helps differentiate it from blocks but its only by a thin margin. I think @bentonam may have some good insight since he has likely written the most code that would benefit from this.

**Comment by bentonam** [comment]
My opinion is that the Alloy configuration itself is predicated on `{` and `}` to clearly define the beginning and end of components and blocks. I think that conditionals should implement this same pattern as well, as a conditional is just a sub-block of code with a clear beginning and end. I also think this would make determining the AST and syntax highlighting simpler, although that is purely a guess.

If the syntax if, else, then, and end are used as strings, would that extend to operators? For example, would `and`, `or`, `eq`, `neq`, `gt`, `gte`, `lt`, `lte`, etc., be used? I would venture to guess no, and that symbols would be used instead: `&&`, `||`, `==`, `!=`, `>`, `>=`, `<`, `<=`.

I also feel that if conditionals are going to be implemented, which I believe they should be, support for a ternary operator should be added at the same time. This would provide a shorthand for what the vast majority of conditionals would be used for anyway.

For example:

```
condition ? 'true_value' : 'false_value';
```

In a practical application: 

```
// prometheus.route inspects incoming metrics and uses their 
// labels to determine which component to forward them to. 
prometheus.route "prod" {
  forward_to = [metric.labels.namespace == "prod" ? prometheus.remote_write.prod.receiver : prometheus.remote_write.default.receiver]
}
```

However, maybe a dynamic reference could be used instead:

```
// prometheus.route inspects incoming metrics and uses their 
// labels to determine which component to forward them to. 
prometheus.route "prod" {
  forward_to = [prometheus.remote_write[metric.labels.namespace].receiver]
}
```

Additionally, I could see a need for case statements as part of conditionals. This would allow for more complex routing and decision-making within the configuration.

**Comment by rfratto** [comment]
I mocked up the proposed grammar for conditionals using curly braces (without any parenthesis around the conditional statement but this message stands either way): 

```
CondExpr       = "if" CondBody CondValue { CondElseIfExpr } [ CondElseExpr ]
CondBody       = Expression 
CondValue      = "{" Expression "}"
CondElseIfExpr = "else" "if" CondBody CondValue
CondElseExpr   = "else" CondValue
```

This led me to notice that `CondValue` is very similar to object literals. I created a (somewhat contrived) example comparing the two proposed syntaxes: 

1. With the `if`/`then`/`else` syntax:

   ```grafana-alloy
   prometheus.remote_write "default" {
     // Parenthesis added for readability.
     external_labels = (
       if env("IS_PROD") == "1" then 
         {
           cluster = "prod", 
           region  = "us-east-1",   
         } 
       else 
         {
           cluster = "non-prod",
           region  = "us-west-1", 
         } 
       end 
     )
   }
   ```

2. With curly braces denoting the expression value:

   ```grafana-alloy
   prometheus.remote_write "default" {
     // Parenthesis added for readability.
     external_labels = (
       if env("IS_PROD") == "1" { 
         {
           cluster = "prod", 
           region  = "us-east-1",   
         } 
       } else { 
         {
           cluster = "non-prod",
           region  = "us-west-1", 
         } 
       }
     )
   }
   ```

I'm concerned that a conditional whose value is an object literally will be somewhat common, and that using curly braces for the conditional value is prone to mistyping: 

```grafana-alloy
prometheus.remote_write "default" {
  // Parenthesis added for readability.
  external_labels = (
    // This is wrong; the outer {} is missing. 
    if env("IS_PROD") == "1" { 
      cluster = "prod",        
      region  = "us-east-1", 
    } else { 
      cluster = "non-prod",
      region  = "us-west-1",
    }
  )
}
```

This could be mitigated in two ways:

* The parser could be aware of this pitfall and create a better error message when an "=" is found inside the body of a conditional. However, the implementation complexity of doing so is slightly beyond trivial.  
* A `return` statement could be added (as suggested by @mattdurham) to more clearly denote the value. However, this is adding complexity not necessary with the if/then/else approach. 

For this reason, I personally think the cons of curly braces now outweigh the pros, and I currently prefer the if/then/else syntax as originally proposed. 

--- 

> I also feel that if conditionals are going to be implemented, which I believe they should be, support for a ternary operator should be added at the same time

@bentonam I can understand the desire for the ternary operator as a familiar concept, but I would prefer to minimize the number of ways one can do conditionals to keep the learning curve as shallow as possible. 

For the same reason, I'm not sure about switch/case statements; I'm not aware of a use case that isn't covered by this proposal (regardless of the syntax) and that can only be covered by ternary operators or switch/case statements.

**Comment by rfratto** [comment]
I've just found an ambiguity with current proposed grammar:

```
CondExpr       = "if" Expression "then" Expression 
                 { CondElseIfExpr } [ CondElseExpr ] "end"
CondElseIfExpr = "else" "if" Expression "then" Expression 
CondElseExpr   = "else" Expression

// CondExpr is a type of PrimaryExpr, giving it one of the lowest precedences.
PrimaryExpr = LiteralValue | ArrayExpr | ObjectExpr | CondExpr  
```

CondElseIfExpr and CondElseExpr are ambiguous, as both derive the token sequence `else if`. Given our grammar is supposed to only require a single lookahead token, this is an issue. 

I can think of a few solutions for this:

1. Introduce a new token for CondElseIfExpr such as `elif`, though that would start to defeat the purpose of using English keywords for conditionals. 

2. Drop the `end` keyword and remove the "else if" concept from the grammar. This means that there would only be "if" and "else", but the else can chain into another conditional:

   ```grafana-alloy 
   if CONDITION1 then VALUE1 
   else if CONDITION2 then VALUE2  
   else if CONDITION3 then VALUE3
   else VALUE4 
   
   // same as: 
   
   if CONDITION1 then VALUE1 
   else (
     if CONDITION2 then VALUE2
     else (
       if CONDITION3 then VALUE3 
       else VALUE 4 
     )
   ) 
   ``` 
   
   This requires dropping the `end` keyword, otherwise you would need one `end` per else-if. Note that the grammar simplification does not necessary change the AST, as the AST could refactor the if-else-if chains into a single AST element.

**Comment by tpaschalis** [comment]
Chiming in with my 2c:

In regard to the braces discussion; I see the arguments from both sides, but the topic of readability and the fact that a single statement is only ever allowed makes me lean towards the no-braces option. I think what we choose here may impact syntax in https://github.com/grafana/alloy/issues/156 as well so we'd be potentially be introducing even more braces scattered around.

In regards to the `elif/no else if` discussion, I find that unfortunate. The root issue here that we only require a single lookahead token but `else if` would be two separate tokens? From the two options presented here, I think the elif option makes more sense; the deep nesting required for even relative simple operations would be easy to break and harder to read IMO.

Does it change anything if we define our grammar as the following instead?
```
CondElseIfExpr = "else" CondExpr 
CondElseExpr   = "else" Expression
```

**Comment by rfratto** [comment]
I've made the following changes to the proposal:

1. I resolved the grammatical ambiguity first noticed in [this hidden comment](https://github.com/grafana/alloy/issues/822#issuecomment-2136038460) by dropping the "else if" production from the grammar and dropping the "end" keyword. There are no differences to how users would write conditionals with the exception of no longer writing the `end` keyword. 

2. Because there is no explicit end marker for conditionals, the section about style and formatting has become stale and was removed; the style and formatting section only applied to making explicit end markers more readable. 

   If consensus moves towards the curly brace form, the style and formatting section would need to be reintroduced, as the curly brace form has an explicit end marker (the closing curly brace `}`). 

For now, I still believe that we should not change to curly brace syntax given my [reasoning](https://github.com/grafana/alloy/issues/822#issuecomment-2135984947) above. 

I also understand the desire for other conditional syntaxes like ternary operator and switch statements, but I believe those are separate proposals and aren't in scope for this discussion. 

cc @mattdurham Does my reasoning above make sense to you? Are you still leaning more towards if/then/else? 

cc others involved in the discussion: @tpaschalis @bentonam @wildum

**Comment by erikbaranowski** [comment]
I see 2 paths forward I would have preference toward. We should take into account what conditional blocks may require and we should be consistent for both syntaxes of conditionals unless there is a very good reason not to. I've provided an example for my 2 preferred options when it comes to curly or not that I think will work for both expressions and blocks. The examples below are for blocks for consideration.

### Curly Braces (CB)

```
if constants.os == "windows" {
  prometheus.exporter.windows {
    ...
  }

  // additional components
} else if constants.os == "linux" {
  promtheus.exporter.unix {
    ...
  }

  // additional components
}
```


### If Else Elif End (IEEE)

Dropping the `end` so that we can keep `else if` limits us to a single expression and falls down for block conditionals that want to include multiple blocks which I expect to be a common use case. In my searching, comparable languages that don't do something comparable to curly braces all make use of `elif` or an equivalent.

```
if constants.os == "windows" then
  prometheus.exporter.windows {
    ...
  }

  // additional components
elif constants.os == "linux" then
  promtheus.exporter.unix {
    ...
  }

  // additional components
end
```

# Opinion Time
It's a bit hard to be objective from here and I recognize the following statements are not:
- CB feels more similar to block and module declares
- IEEE is closer to english but requires someone to know which of the commonly used `else if` usages are valid such as `elif` vs `elsif` vs `elseif`
- Either option is legible to me and reasonable for someone creating conditional config to read/write

If you twisted my arm today, I would probably vote for curly braces. I don't find the closer to english argument for IEEE alone super compelling in this case since we are talking about if conditionals that are an entry level programming concept and commonly done with CB in other languages. That said, I'm 99% happy to move forward with IEEE as long as we don't drop the end.

**Comment by rfratto** [comment]
After a long helpful chat with @erikbaranowski and @hedss, I realized there's multiple factors impacting how we design conditional values:

* The concept of conditionally defining blocks ("conditional blocks") 
* The concept of "component scheduling" where you can disable components on non-owning nodes within a cluster (a long-running goal @tpaschalis has been thinking about)
  * (Based on what I've heard so far from @tpaschalis, component scheduling is extremely similar to component blocks, and we may want to consider combining the two concepts to avoid duplicate solutions)  
* Optionally supporting Alloy configuration via YMAL syntax (a goal of mine I plan to have a proposal for in the upcoming months)

These other goals are relevant to conditional value because we aim for consistency and minimalism with Alloy's syntax. 

So far, the discussion about curly braces has largely depended on conjecture for how conditional blocks _might_ be designed. Designing on conjecture can be particularly bad for syntax, as syntax is hard to change and conjecture may lead to weaker choices based on scenarios that never happen. 

As my proposal is now, I think it's under-baked and doesn't give enough consideration to the other goals we have that impact the design of conditionals. For now, I'm going to close this proposal and give time for some of the other goals to be solved first. I'll return later with a refreshed proposal once it becomes more feasible to evaluate the conditionals design.
