### ISSUE TITLE
Docs feedback: Scrape jobs can't authenticate with K8s

### ISSUE THREAD

**Issue by vnugent** [grafana/alloy#827]
### URL

https://grafana.com/docs/alloy/latest/tasks/configure/configure-kubernetes/

### Feedback

I’m following the [Kubernetes docs](https://grafana.com/docs/alloy/latest/tasks/configure/configure-kubernetes/)  to deploy Alloy on a k8s cluster.  The alloy pods are running ok but they can’t authenticate with k8s.
```
ts=2024-05-10T17:24:12.68722559Z level=debug msg="Scrape failed" 
component_path=/ component_id=prometheus.scrape.default scrape_pool=prometheus.scrape.default 
target=http://172.31.5.182:10250/metrics err="server returned HTTP status 400 Bad Request
```
[This article](https://medium.com/@stepanvrany/i-replaced-several-kubernetes-components-with-grafana-agent-flow-heres-how-74ecdc60bffe) helps a lot.  It's not documented anywhere in the official docs.

```hcl
discovery.relabel "metrics_kubelet" {
...
}

prometheus.scrape "kubelet" {
        scheme = "https"
        tls_config {
            server_name = "kubernetes"
            ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            insecure_skip_verify = false
        }
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
 ...       
}
```

**Comment by hainenber** [comment]
I made a PR to add an `prometheus.scrape` example for K8s auth. Let me know if it's looks good to you :D
