### ISSUE TITLE
How to add the container label for cadvisr

### ISSUE THREAD

**Issue by bingkunyangvungle** [grafana/alloy#830]
### URL

https://github.com/grafana/alloy/blob/9f6bc3a1ab553fd25c439dab1b148cb0736e59ba/docs/sources/reference/components/prometheus.exporter.cadvisor.md

### Feedback

I'm currently using `prometheus.exporter.cadvisor "cadvisor"` to get the related metrics. The metric can show up, but when I was trying to add the labels using the following configuration:
```
allowlisted_container_labels = ["io.kubernetes.container.name", "io.kubernetes.pod.name", "io.kubernetes.pod.namespace"]
```
The label doesn't show up in the metrics. I've already set this: `store_container_labels = false` because in the doc, it mentioned:
```
For allowlisted_container_labels to take effect, store_container_labels must be set to false.
```
Could anyone help to look into this and provide some guideline? Thank you.

**Comment by ptodev** [comment]
Could this be because the labels contain dots? Prometheus labels are [quite strict](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) with what characters are allowed in them. Could you try a label such as `io_kubernetes_container_name`?

**Comment by bingkunyangvungle** [comment]
Thank you @ptodev , I just tried with your suggestion `io_kubernetes_container_name` and it still returns error:
```
Error: /etc/alloy/config.alloy:82:37: component "io_kubernetes_container_name" does not exist or is out of scope
81 |     store_container_labels = false
82 |     allowlisted_container_labels = [io_kubernetes_container_name]
   |                                     ^
83 | }
```
Not sure what this one was. And it's not in the doc as we.

**Comment by ptodev** [comment]
You're missing the quotation marks :)
```
allowlisted_container_labels = ["io_kubernetes_container_name"]
```

**Comment by bingkunyangvungle** [comment]
Oh my, this is the cause. Really appreciate for your help! @ptodev

**Comment by bingkunyangvungle** [comment]
The issue resolves. But the metrics doesn't appear neither. Still need more investigation.

**Comment by ptodev** [comment]
Hi @bingkunyangvungle, out of curiosity - how did you resolve the issue?
