### ISSUE TITLE
Debian 12: v1.1.0: panic loop

### ISSUE THREAD

**Issue by dotwaffle** [grafana/alloy#868]
### What's wrong?

Installed v1.0.0 a couple of weeks ago, with Docker integration it was spamming a lot of logs (>10GB/day or almost 100x the previous rate) so I disabled Alloy. I saw notes saying that this happened when using Docker Swarm with multiple networks.

On upgrading to v1.1.0 yesterday, now Alloy sits in a panic loop.

### Steps to reproduce

Not 100% sure, but I think having a Docker Swarm single-node cluster enabled, and a number of stacks that have multiple docker networks triggers it. Happy to help debug if you reset my logs quota if/when it goes over ;)

### System information

Debian 12, amd64 (using rsyslog as upgrade from Debian 11 and 10 before that)

### Software version

Grafana Alloy v1.1.0

### Configuration

```text
Standard config with docker extension and node exporter setup.
```

### Logs

```text
May 15 12:43:58 very alloy[75533]: ts=2024-05-15T12:43:58.439250819Z level=info msg="tail routine: started" component_path=/ component_id=loki.source.file.logs_integrations_integrations_node_exporter_direct_scrape component=tailer path=/var/log/user.log
May 15 12:43:58 very alloy[75533]: ts=2024-05-15T12:43:58.439259996Z level=info msg="Seeked /var/log/user.log - &{Offset:0 Whence:0}" component_path=/ component_id=loki.source.file.logs_integrations_integrations_node_exporter_direct_scrape
May 15 12:44:08 very alloy[75533]: ts=2024-05-15T12:44:08.439937148Z level=error msg="error inspecting Docker container" target=5b71a3bd08c329e1c6cc46be0e448861f7cace88f2e7956d8d86fa122a03481a component_path=/ component_id=loki.source.docker.logs_integrations_docker id=5b71a3bd08c329e1c6cc46be0e448861f7cace88f2e7956d8d86fa122a03481a error="Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.44/containers/5b71a3bd08c329e1c6cc46be0e448861f7cace88f2e7956d8d86fa122a03481a/json\": context canceled"
May 15 12:44:08 very alloy[75533]: panic: runtime error: invalid memory address or nil pointer dereference
May 15 12:44:08 very alloy[75533]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3d4cc7e]
May 15 12:44:08 very alloy[75533]: goroutine 922 [running]:
May 15 12:44:08 very alloy[75533]: github.com/grafana/alloy/internal/component/loki/source/docker/internal/dockertarget.(*Target).Stop(0xc003d10900)
May 15 12:44:08 very alloy[75533]:         /drone/src/internal/component/loki/source/docker/internal/dockertarget/target.go:238 +0x1e
May 15 12:44:08 very alloy[75533]: github.com/grafana/alloy/internal/component/loki/source/docker.(*tailer).Run(0xc0032144e0, {0x8e87d40, 0xc00595ef50})
May 15 12:44:08 very alloy[75533]:         /drone/src/internal/component/loki/source/docker/runner.go:116 +0x2f8
May 15 12:44:08 very alloy[75533]: github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks.func2()
May 15 12:44:08 very alloy[75533]:         /drone/src/internal/runner/runner.go:166 +0x90
May 15 12:44:08 very alloy[75533]: created by github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks in goroutine 192
May 15 12:44:08 very alloy[75533]:         /drone/src/internal/runner/runner.go:163 +0x585
May 15 12:44:08 very systemd[1]: alloy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 15 12:44:08 very systemd[1]: alloy.service: Failed with result 'exit-code'.
May 15 12:44:08 very systemd[1]: alloy.service: Consumed 2.191s CPU time.
May 15 12:44:08 very systemd[1]: alloy.service: Scheduled restart job, restart counter is at 6.
May 15 12:44:08 very systemd[1]: Stopped alloy.service - Vendor-agnostic OpenTelemetry Collector distribution with programmable pipelines.
May 15 12:44:08 very systemd[1]: alloy.service: Consumed 2.191s CPU time.
May 15 12:44:08 very systemd[1]: Started alloy.service - Vendor-agnostic OpenTelemetry Collector distribution with programmable pipelines.
May 15 12:44:08 very alloy[76043]: ts=2024-05-15T12:44:08.783796375Z level=info "boringcrypto enabled"=false
```

**Comment by rfratto** [comment]
Thanks for reporting! I'm guessing the panic here is related to #742 (cc @wildum), but I don't think we've explicitly made any changes for 1.1 related to log volume and Docker Swarm networks. Once we fix the panic, I'd exercise a little caution about where logs are sent when testing the component (maybe a short lived local Loki cluster?) to avoid any repeat log volume issues. 

> Not 100% sure, but I think having a Docker Swarm single-node cluster enabled, and a number of stacks that have multiple docker networks triggers it. Happy to help debug if you reset my logs quota if/when it goes over ;)

I'm sorry there was something with 1.0 that caused you to go over your logs quota. I'd recommend talking to Grafana Cloud support and seeing what they can do for your quota here, especially if you hit the limit thanks to a bug. Unfortunately this isn't something I can personally help with, but I am sympathetic to how frustrating this would be.

**Comment by dotwaffle** [comment]
Sorry, it was a tongue in cheek comment, I've already been in touch with Grafana Cloud and they've adjusted things.

Most of the log volume being sent was related to Alloy (as in, more than half of the lines in /var/log/syslog had the string "alloy" in it), much of it related to Docker, which is why I mentioned it as the stack trace appeared to mention an NPE related to Docker.

Happy to help debug if there's a branch you recommend I install?

**Comment by wildum** [comment]
Hello, thanks for reporting the bug and sorry about that. I think that I have a fix for it: https://github.com/grafana/alloy/pull/875.

**Comment by nicoluca** [comment]
Had the same issue, indeed https://github.com/grafana/alloy/pull/875 seems to fix it, thanks @wildum.

**Comment by dotwaffle** [comment]
I picked up the latest update tonight via the apt repo, and the issue appears to be resolved. Thanks all!
