### ISSUE TITLE
Alloy pulling dependency with BUSL-1.1 license

### ISSUE THREAD

**Issue by johanneskastl** [grafana/alloy#899]
I am preparing a package of alloy for openSUSE. During the checks one question regarding the licensing came up, as one of the dependencies contains BUSL-1.1 licensed code.

IANAL, but normally this means that we cannot package this, as the code could potentially be BUSL-1.1 licensed.

The dependency in question is `vendor/github.com/hashicorp/vault/api/auth/gcp/LICENSE`

- https://github.com/grafana/alloy/blob/main/go.mod#L79
- https://github.com/hashicorp/vault/blob/main/LICENSE#L51

Thanks in advance!

**Comment by proffalken** [comment]
Also not a lawyer, however [the hashicorp FAQ on this](https://www.hashicorp.com/blog/hashicorp-updates-licensing-faq-based-on-community-questions) seems to suggest some of these libraries may have been assigned BUSL by accident and will revert to MPL at some point.

The BUSL also seems to only apply to the code that is explicitly covered by it, so even if I've read it wrong, Alloy remains under the original license and only the vault library is BUSL?

```
HashiCorp adopted the BSL for only our core products. The HashiCorp APIs, SDKs, Terraform providers, and almost all other libraries across the HashiCorp portfolio will remain licensed under Mozilla Public License v2.0 (MPL 2.0). There are a few libraries, such as Vault Shamir, that were inadvertently re-licensed because of the monorepo approach, but we’ve since explicitly licensed those back to MPL. We thank community members for bringing this to our attention. The BSL license is also compatible with most other licenses and, with the exception of certain copyleft licenses such as GPL, does not prevent using HashiCorp products as part of other OSS projects.
```

Don't get me wrong, I wish Hashi had taken a different approach here, and you'll need legal support to confirm my thoughts, but I *think* you might be ok?

**Comment by johanneskastl** [comment]
> Also not a lawyer, however [the hashicorp FAQ on this](https://www.hashicorp.com/blog/hashicorp-updates-licensing-faq-based-on-community-questions) seems to suggest some of these libraries may have been assigned BUSL by accident and will revert to MPL at some point.
> 
> The BUSL also seems to only apply to the code that is explicitly covered by it, so even if I've read it wrong, Alloy remains under the original license and only the vault library is BUSL?
> 
> ```
> HashiCorp adopted the BSL for only our core products. The HashiCorp APIs, SDKs, Terraform providers, and almost all other libraries across the HashiCorp portfolio will remain licensed under Mozilla Public License v2.0 (MPL 2.0). There are a few libraries, such as Vault Shamir, that were inadvertently re-licensed because of the monorepo approach, but we’ve since explicitly licensed those back to MPL. We thank community members for bringing this to our attention. The BSL license is also compatible with most other licenses and, with the exception of certain copyleft licenses such as GPL, does not prevent using HashiCorp products as part of other OSS projects.
> ```
> 
> Don't get me wrong, I wish Hashi had taken a different approach here, and you'll need legal support to confirm my thoughts, but I _think_ you might be ok?

Sorry, I must have missed the notification on your reply. Only got a notice of the bot comment.

I just had a look at the header of the actual go file `api/auth/gcp/gcp.go` which apparently had a MPL2.0 header since March last year:

https://github.com/hashicorp/vault/blame/main/api/auth/gcp/gcp.go

So it might just be some confusing on the repo being licensed BUSL-1.1 with some files being licensed differently.

Thanks for your input, @proffalken 

Kind Regards,
Johannes
