### ISSUE TITLE
Import git ssh error silenced

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#914]
The SSH key conversion does not surface the error: https://github.com/grafana/alloy/blob/main/internal/vcs/auth.go#L29

When this happens, the given ssh key will be ignored and the go-git will try to use the ssh-agent instead: https://github.com/go-git/go-git/blob/master/plumbing/transport/ssh/common.go#L39

This is not good:

- if the key that I pass is wrong but the ssh-agent is correctly setup, then it will work but I won't know that I passed wrong information. It's also not using the auth method that I wanted.
- if the key is wrong and the ssh-agent is not set, then I will get an error related to the ssh-agent. I won't know what's wrong my ssh key which makes it super hard to debug

**Comment by csh0101** [comment]
what is ssh-agent?

**Comment by wildum** [comment]
It'a a key manager for SSH, have a look at https://smallstep.com/blog/ssh-agent-explained/
